
DROP TABLE IF EXISTS `voters`;
CREATE TABLE `voters` (
  `id` int(11) NOT NULL,
  `username` varchar(60) DEFAULT NULL,
  `name` varchar(60) DEFAULT NULL,
  `company` varchar(60) DEFAULT NULL,
  `employee_id` varchar(60) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `voters` (`id`,`username`,`name`,`company`,`employee_id`) VALUES
(1, 'Szaboadm', 'Szabó István', 'RAS Magyarország Kft.', 'istvan.szabo@ringieraxelspringer.hu'),
(2, 'ispi', 'Ispán László', 'RAS Magyarország Kft.', 'laszlo.ispan@ringieraxelspringer.hu'),
(3, 'Winkler.Peter', 'Winkler Péter', 'RAS Magyarország Kft.', 'peter.winkler@ringieraxelspringer.hu'),
(4, 'Nemeth.Richard', 'Németh Richárd', 'RAS Magyarország Kft.', 'richard.nemeth@ringieraxelspringer.hu'),
(5, 'Zimmer.Helga', 'Dr. Zimmer Helga', 'RAS Magyarország Kft.', 'helga.zimmer@ringieraxelspringer.hu'),
(6, 'Viszmeg.Katalin', 'Viszmeg Katalin', 'RAS Magyarország Kft.', 'katalin.viszmeg@ringieraxelspringer.hu'),
(7, 'Bokor.Klara', 'Bokor Klára', 'RAS Magyarország Kft.', 'klara.bokor@ringieraxelspringer.hu'),
(8, 'Kepe.Judit', 'Képe Judit', 'RAS Magyarország Kft.', 'judit.kepe@ringieraxelspringer.hu'),
(9, 'Vodnyanszky.Eva', 'Vodnyánszky Éva', 'RAS Magyarország Kft.', 'eva.vodnyanszky@ringieraxelspringer.hu'),
(10, 'Schweiczer.Timea', 'Schweiczer Tímea Aina', 'RAS Magyarország Kft.', 'timea.schweiczer@ringieraxelspringer.hu'),
(11, 'Soltesz.Mihaly', 'Soltész Mihály', 'RAS Magyarország Kft.', 'mihaly.soltesz@ringieraxelspringer.hu'),
(12, 'Ratkai.Krisztina', 'Ratkai Krisztina', 'RAS Magyarország Kft.', 'krisztina.ratkai@ringieraxelspringer.hu'),
(13, 'Stefanek.Aranka', 'Stefanek Aranka', 'RAS Magyarország Kft.', 'aranka.stefanek@ringieraxelspringer.hu'),
(14, 'Pap.Annamaria', 'Pap Annamária', 'RAS Magyarország Kft.', 'anna.pap@ringieraxelspringer.hu'),
(15, 'Torda.Istvan', 'Torda István', 'AS-B Kft.', 'istvan.torda@raspartner.hu'),
(16, 'Nagy.Sandor', 'Nagy Sándor', 'RAS Magyarország Kft.', 'sandor.nagy@ringieraxelspringer.hu'),
(17, 'Gazdag.Erzsebet', 'Gazdag Erzsébet', 'RAS Magyarország Kft.', 'erzsebet.gazdag@ringieraxelspringer.hu'),
(18, 'Ivanyi.Geza', 'Iványi Géza', 'RAS Magyarország Kft.', 'geza.ivanyi@ringieraxelspringer.hu'),
(19, 'Szuts.Petra', 'Szűts Petra', 'RAS Magyarország Kft.', 'petra.szuts@ringieraxelspringer.hu'),
(20, 'Pollak.Andrea', 'Pollák Andrea', 'RAS Magyarország Kft.', 'andrea.pollak@ringieraxelspringer.hu'),
(21, 'Dus.Agnes', 'Dús Ágnes', 'RAS Magyarország Kft.', 'agnes.dus@raspartner.hu'),
(22, 'Schwang.Laszlo', 'Schwang László', 'RAS Magyarország Kft.', 'laszlo.schwang@ringieraxelspringer.hu'),
(23, 'Peter.Jozsef', 'Péter József', 'AS-B Kft.', 'jozsef.peter@raspartner.hu'),
(24, 'Kover.Nora', 'Kövér Nóra', 'RAS Magyarország Kft.', 'nora.kover@ringieraxelspringer.hu'),
(25, 'Balogh.Agnes', 'Balogh Ágnes', 'RAS Magyarország Kft.', 'agi.balogh@ringieraxelspringer.hu'),
(26, 'Derenyi.Tamas', 'Derényi Tamás', 'RAS Magyarország Kft.', 'tamas.derenyi@ringieraxelspringer.hu'),
(27, 'Horvath.Sara', 'Horváth Sára', 'Chabek Kft. ; megbízó:RAS Mo. Kft.', 'sara.horvath@raspartner.hu'),
(28, 'Wimmer.Anita', 'Wimmer Anita', 'RAS Magyarország Kft.', 'anita.wimmer@ringieraxelspringer.hu'),
(29, 'Mihalyi.Miklos', 'Mihályi Miklós', 'RAS Magyarország Kft.', 'miklos.mihalyi@ringieraxelspringer.hu'),
(30, 'Soos.Barbara', 'Drávai Barbara', 'AS-B Kft.', 'barbara.soos@raspartner.hu'),
(31, 'Egri.Marta', 'Egri Márta', 'AS-B Kft.', 'marti.egri@raspartner.hu'),
(32, 'Nemeth.Eva', 'Németh Éva', 'AS-B Kft.', 'eva.nemeth@raspartner.hu'),
(33, 'Tanos.Eva', 'Tanos Éva', 'AS-B Kft.', 'eva.tanos@raspartner.hu'),
(34, 'Kalmar.Peter', 'Kalmár Péter', 'AS-B Kft', 'peter.kalmar@raspartner.hu'),
(35, 'Zsanko.Zsuzsanna', 'Zsankó Zsuzsanna', 'RAS Magyarország Kft.', 'zsuzsa.zsanko@raspartner.hu'),
(36, 'Striho.Zsuzsa', 'Strihó Zsuzsa', 'RAS Magyarország Kft.', 'zsuzsa.striho@raspartner.hu'),
(37, 'Kiraly.Maria', 'Dr. Király Mária', 'RAS Magyarország Kft.', 'maria.kiraly@ringieraxelspringer.hu'),
(38, 'Dr.Bayer.Jozsef', 'Dr. Bayer József', 'RAS Magyarország Kft.', 'jozsef.bayer@ringieraxelspringer.hu'),
(39, 'Gajdos.Istvan', 'Gajdos István', 'RAS Magyarország Kft.', 'istvan.gajdos@ringieraxelspringer.hu'),
(40, 'Szucs.Istvan2', 'Szűcs István', 'RAS Magyarország Kft.', 'istvan.szucs1@ringieraxelspringer.hu'),
(41, 'Olah.Csaba', 'Oláh Csaba', 'RAS Magyarország Kft.', 'csaba.olah@ringieraxelspringer.hu'),
(42, 'Szucs.Istvan', 'Szűcs István', 'AS-B Kft.', 'istvan.szucs@raspartner.hu'),
(43, 'Pataky.Eva', 'Pataky Éva', 'RAS Magyarország Kft.', 'eva.pataky@ringieraxelspringer.hu'),
(44, 'Hidvary.Peter', 'Hídváry Péter', 'RAS Magyarország Kft.', 'peter.hidvary@ringieraxelspringer.hu'),
(45, 'B.Toth.Agnes', 'B. Tóth Ágnes', 'AS-B Kft.', 'agnes.btoth@raspartner.hu'),
(46, 'Graner.Istvan', 'Gráner István', 'AS-B Kft.', 'istvan.graner@raspartner.hu'),
(47, 'Ban.Judit', 'Bán Judit', 'RAS Magyarország Kft.', 'judit.ban@ringieraxelspringer.hu'),
(48, 'Kerekes.Ildiko', 'Kerekes Ildikó', 'RAS Magyarország Kft.', 'janosne.kerekes@ringieraxelspringer.hu'),
(49, 'Berta.Bernadett', 'Berta Bernadett', 'RAS Magyarország Kft.', 'bernadett.berta@ringieraxelspringer.hu'),
(50, 'Kenyeres.Zoltan', 'Kenyeres Zoltán', 'RAS Magyarország Kft.', 'zoltan.kenyeres@ringieraxelspringer.hu'),
(51, 'Sodar.Jozsef', 'Sódar József', 'RAS Magyarország Kft.', 'jozsef.sodar@ringieraxelspringer.hu'),
(52, 'Szilagyi.Gabor', 'Szilágyi Gábor', 'RAS Magyarország Kft.', 'gabor.szilagyi@ringieraxelspringer.hu'),
(53, 'Berenyi.Andras', 'Berényi András', 'RAS Magyarország Kft.', 'andras.berenyi@ringieraxelspringer.hu'),
(54, 'Pinter.Judit', 'Pintér Judit', 'RAS Magyarország Kft.', 'judit.pinter@ringieraxelspringer.hu'),
(55, 'Kokeny.Nikoletta', 'Kökény Nikoletta', 'AS-B Kft.', 'nikoletta.kokeny@raspartner.hu'),
(56, 'Smiri.Andrea', 'Smiri Andrea', 'RAS Magyarország Kft.', 'smiri.andrea@ringieraxelspringer.hu'),
(57, 'Sarai.Maria', 'Sárai Mária', 'RAS Magyarország Kft.', 'maria.sarai@ringieraxelspringer.hu'),
(58, 'Tap.Krisztina', 'Táp Krisztina', 'RAS Magyarország Kft.', 'krisztina.tap@ringieraxelspringer.hu'),
(59, 'nyiro.zsolt', 'Nyírő Zsolt', 'RAS Magyarország Kft.', 'zsolt.nyiro@ringieraxelspringer.hu'),
(60, 'Kovacs.Violetta', 'Kovács Violetta', 'RAS Magyarország Kft.', 'violetta.kovacs@ringieraxelspringer.hu'),
(61, 'Szlancsik.Janos', 'Szlancsik János', 'RAS-NYOMDA Nyomdaipari Kft.', 'janos.szlancsik@ringieraxelspringer.hu'),
(62, 'Lantos.Ferenc', 'Lantos Ferenc', 'RAS Magyarország Kft.', 'ferenc.lantos@ringieraxelspringer.hu'),
(63, 'Nagy.Edina', 'Nagy Edina', 'RAS Magyarország Kft.', 'edina.nagy@ringieraxelspringer.hu'),
(64, 'Szabo.Bernadett', 'Szabó Bernadett', 'AS-B Kft.', 'bernadett.szabo@raspartner.hu'),
(65, 'Szabados.Balazs', 'Szabados Balázs', 'RAS Magyarország Kft.', 'balazs.szabados@ringieraxelspringer.hu'),
(66, 'Kortvelyesi.Csaba', 'Körtvélyesi Csaba', 'RAS Magyarország Kft.', 'csaba.kortvelyesi@ringieraxelspringer.hu'),
(67, 'Erki.Tamas', 'Erki Tamás', 'RAS Magyarország Kft.', 'tamas.erki@ringieraxelspringer.hu'),
(68, 'Maroy.Krisztina', 'Maróy Krisztina', 'RAS Magyarország Kft.', 'krisztina.maroy@ringieraxelspringer.hu'),
(69, 'Schneider.Zoltan', 'Schneider Zoltán', 'RAS Magyarország Kft.', 'zoltan.schneider@ringieraxelspringer.hu'),
(70, 'Csati.Melinda', 'Csáti Melinda', 'RAS Magyarország Kft.', 'melinda.csati@ringieraxelspringer.hu'),
(71, 'Beleznay.Ibolya', 'Beleznay Ibolya', 'NYPD Invest Kft.', 'ibolya.beleznay@raspartner.hu'),
(72, 'Horvath.Gergely2', 'Horváth Gergő', 'RAS Magyarország Kft.', 'gergo.horvath@ringieraxelspringer.hu'),
(73, 'Toth.Gergo', 'Tóth Gergő', 'RAS Magyarország Kft.', 'gergo.toth@ringieraxelspringer.hu'),
(74, 'Vasko.Beatrix', 'Vaskó Beatrix', 'HarperCollins Magyarország Kft.', 'beatrix.vasko@harpercollins.hu'),
(75, 'Lieberman.Klara', 'Lieberman Klára', 'RAS Magyarország Kft.', 'klara.lieberman@raspartner.hu'),
(76, 'Mate.Eva', 'Máté Éva', 'AS-B Kft.', 'eva.mate@raspartner.hu'),
(77, 'Porta', 'Porta - Városmajor utca 11.', 'RAS Magyarország Kft.', 'rasporta@ringieraxelspringer.hu'),
(78, 'Seres.Gabriella', 'Seres Gabriella', 'RAS Magyarország Kft.', 'gabriella.seres@ringieraxelspringer.hu'),
(79, 'Gajdos.Monika', 'Gajdos Mónika', 'RAS Magyarország Kft.', 'monika.gajdos@ringieraxelspringer.hu'),
(80, 'Szoverfy.Csilla', 'Szövérfy Csilla', 'RAS Magyarország Kft.', 'csilla.szoverfy@ringieraxelspringer.hu'),
(81, 'Falvi.Krisztina', 'Falvi Krisztina', 'RAS Magyarország Kft.', 'krisztina.falvi@ringieraxelspringer.hu'),
(82, 'Udvari.Gabriella', 'Udvari Gabriella', 'RAS Magyarország Kft.', 'gabriella.udvari@ringieraxelspringer.hu'),
(83, 'Bayer.Ferenc', 'Bayer Ferenc', 'RAS Magyarország Kft.', 'ferenc.bayer@ringieraxelspringer.hu'),
(84, 'Bago.Istvan', 'Bagó István', 'RAS Magyarország Kft.', 'istvan.bago@ringieraxelspringer.hu'),
(85, 'Nemeth.Zsuzsa', 'Németh Zsuzsanna', 'RAS Magyarország Kft.', 'zsuzsanna.nemeth@ringieraxelspringer.hu'),
(86, 'Csendes.Eszter', 'Csendes Eszter', 'RAS Magyarország Kft.', 'eszter.csendes@ringieraxelspringer.hu'),
(87, 'Jelen.Szilvia', 'Jelen Szilvia', 'RAS Magyarország Kft.', 'szilvia.jelen@ringieraxelspringer.hu'),
(88, 'Kugler.Tunde', 'Kugler Tünde', 'RAS Magyarország Kft.', 'tunde.kugler@ringieraxelspringer.hu'),
(89, 'Czifra.Anna', 'Czifra Anna', 'Dealdone Kommunikációs Kft', 'anna.czifra@raspartner.hu'),
(90, 'Szatmari.Andrea', 'Bíró Andrea', 'RAS Magyarország Kft.', 'andrea.biro@ringieraxelspringer.hu'),
(91, 'Kucselata.Ildiko', 'Kucselata Ildikó', 'RAS Magyarország Kft.', 'ildiko.kucselata@ringieraxelspringer.hu'),
(92, 'Fejes.Gyorgyi', 'Fejes Györgyi', 'RAS Magyarország Kft.', 'gyorgyi.fejes@ringieraxelspringer.hu'),
(93, 'Vincze.Viktoria', 'Vincze Viktória', 'RAS Magyarország Kft.', 'viktoria.vincze@ringieraxelspringer.hu'),
(94, 'Racz.Zita', 'Rácz Zita', 'RAS Magyarország Kft.', 'zita.racz@ringieraxelspringer.hu'),
(95, 'Radai.Gabor', 'Rádai Gábor', 'RAS Magyarország Kft.', 'gabor.radai@ringieraxelspringer.hu'),
(96, 'Szollosi.Bela', 'Szöllősi Béla', 'RAS Magyarország Kft.', 'bela.szollosi@ringieraxelspringer.hu'),
(97, 'Farago.Tamas', 'Faragó Tamás', 'RAS-NYOMDA Nyomdaipari Kft.', 'tamas.farago@ringieraxelspringer.hu'),
(98, 'Boros.Jozsef', 'Boros József', 'RAS-NYOMDA Nyomdaipari Kft.', 'jozsef.boros@ringieraxelspringer.hu'),
(99, 'Kassai.Monika', 'Kassai Mónika', 'RAS Magyarország Kft.', 'monika.kassai@ringieraxelspringer.hu'),
(100, 'molnar.jozsef.am', 'Molnár József', 'RAS Magyarország Kft.', 'jozsef.molnar@ringieraxelspringer.hu'),
(101, 'Szalai.Erzsebet', 'Szalainé Sima Erzsébet', 'RAS-NYOMDA Nyomdaipari Kft.', 'erzsebet.szalai@ringieraxelspringer.hu'),
(102, 'Szucs.Laszlo', 'Szűcs László', 'AS-B Kft.', 'laszlo.szucs@raspartner.hu'),
(103, 'Balo.Peter', 'Baló Péter', 'RAS Magyarország Kft.', 'peter.balo@ringieraxelspringer.hu'),
(104, 'Kerekes.Anna', 'Kerekes Anna', 'RAS Magyarország Kft.', 'anna.kerekes@ringieraxelspringer.hu'),
(105, 'Nyusti.Katalin', 'Nyusti Katalin', 'RAS Magyarország Kft.', 'kati.nyusti@ringieraxelspringer.hu'),
(106, 'Laky.Judit', 'Laki Judit', 'Surda Bt', 'judit.laki@raspartner.hu'),
(107, 'Kissne.Klara', 'Kissné Kosztolányi Klára', 'Harlequin Magyarország Kft.', 'klara.kissne@raspartner.hu'),
(108, 'Bakay.Dora', 'Bakay Dóra', 'Harlequin Magyarország Kft.', 'dora.bakay@raspartner.hu'),
(109, 'Lukacs.Annabella', 'Lukács Annabella', 'RAS Magyarország Kft.', 'Annabella.Lukacs@raspartner.hu'),
(110, 'Pataki.Zsolt', 'Pataki Zsolt', 'RAS Magyarország Kft.', 'zsolt.pataki@raspartner.hu'),
(111, 'Deli.Krisztina', 'Deli Krisztina', 'RAS Magyarország Kft.', 'krisztina.deli@ringieraxelspringer.hu'),
(112, 'Gellen.Csaba', 'Gellén Csaba', 'RAS Magyarország Kft.', 'csaba.gellen@ringieraxelspringer.hu'),
(113, 'Szabo.Laszlo2', 'Szabó László', 'RAS Magyarország Kft.', 'laszlo.szabo2@ringieraxelspringer.hu'),
(114, 'Czigany.Mihaly', 'Czigány Mihály', 'RAS-NYOMDA Nyomdaipari Kft.', 'mihaly.czigany@ringieraxelspringer.hu'),
(115, 'Ifj.Nemes.Peter', 'Ifj. Nemes Péter', 'AS-B Kft.', 'peter.nemes.ifj@raspartner.hu'),
(116, 'erdos.krisztina', 'Erdős Krisztina', 'RAS Magyarország Kft.', 'krisztina.erdos@raspartner.hu'),
(117, 'Egri.Klara', 'Egri Klára', 'RAS Magyarország Kft.', 'klara.egri@ringieraxelspringer.hu'),
(118, 'Kormany.Ildiko', 'Kormány Ildikó', 'RAS Magyarország Kft.', 'ildiko.kormany@ringieraxelspringer.hu'),
(119, 'Heiser.Krisztina', 'Heiser Krisztina', 'HarperCollins Magyarország Kft.', 'krisztina.heiser@harpercollins.hu'),
(120, 'Bogyine.Etelka', 'Bógyiné Hegedűs Etelka', 'RAS Magyarország Kft.', 'etelka.bogyine@ringieraxelspringer.hu'),
(121, 'Kerek.Agnes', 'Kerék Ágnes', 'RAS Magyarország Kft.', 'agnes.kerek@ringieraxelspringer.hu'),
(122, 'Balogh.Mariann', 'Fekésháziné Balog Marianna', 'RAS Magyarország Kft.', 'mariann.balog@ringieraxelspringer.hu'),
(123, 'Holczer.Angela', 'Holczer Angéla', 'RAS Magyarország Kft.', 'angela.holczer@ringieraxelspringer.hu'),
(124, 'Dr.Laufer.Judit', 'Dr. Laufer Judit', 'AS-B Kft.', 'judit.laufer@raspartner.hu'),
(125, 'Barna.Krisztian', 'Barna Krisztián', 'RAS-NYOMDA Nyomdaipari Kft.', 'krisztian.barna@ringieraxelspringer.hu'),
(126, 'Kormany.Andrea', 'Kormány Andrea', 'RAS-NYOMDA Nyomdaipari Kft.', 'andrea.kormany@ringieraxelspringer.hu'),
(127, 'Eletmodlapok.Kulsos', 'Életmódlapok Külsős', 'RAS Magyarország Kft.', 'eletmódlapok.kulsos@raspartner.hu'),
(128, 'zsikla.janos', 'Zsikla János', 'RAS-NYOMDA Nyomdaipari Kft.', 'janos.zsikla@ringieraxelspringer.hu'),
(129, 'Szilagyi.Viktor', 'Szilágyi Viktor', 'RAS Magyarország Kft.', 'viktor.szilagyi@ringieraxelspringer.hu'),
(130, 'Hajdu.Peter', 'Hajdu Péter', 'RAS Magyarország Kft.', 'peter.hajdu@ringieraxelspringer.hu'),
(131, 'Kovacs.Csilla', 'Kovács Csilla', 'RAS Magyarország Kft.', 'csilla.kovacs@ringieraxelspringer.hu'),
(132, 'Kun.Krisztina', 'Kun Krisztina', 'RAS Magyarország Kft.', 'krisztina.kun@ringieraxelspringer.hu'),
(133, 'Dr.Marunak.Istvanne', 'Dr. Marunák Istvánné', 'RAS Magyarország Kft.', 'istvanne.marunak@ringieraxelspringer.hu'),
(134, 'Csatari.Sandor', 'Csatári Sándor', 'RAS Magyarország Kft.', 'sandor.csatari@ringieraxelspringer.hu'),
(135, 'nagy-gyorgy.borbala', 'Nagy-György Borbála', 'RAS Magyarország Kft.', 'borbala.nagy-gyorgy@ringieraxelspringer.hu'),
(136, 'alexa.istvan', 'Alexa István', 'RAS Magyarország Kft.', 'istvan.alexa@ringieraxelspringer.hu'),
(137, 'hirdetes.gyakornok2', 'Hirdetés Gyakornok 2', 'AS-B Kft.', 'hirdetes.gyakornok2@raspartner.hu'),
(138, 'hirdetes.gyakornok3', 'Hirdetés Gyakornok 3', 'AS-B Kft.', 'hirdetes.gyakornok3@raspartner.hu'),
(139, 'Hirdetes.Gyakornok4', 'Hirdetés Gyakornok 4', 'AS-B Kft.', 'hirdetes.gyakornok4@raspartner.hu'),
(140, 'Demeter.Csilla', 'Demeter Csilla', 'RAS Magyarország Kft.', 'csilla.demeter@ringieraxelspringer.hu'),
(141, 'Moharos.Andrea', 'Moharos Andrea', 'RAS Magyarország Kft.', 'andrea.moharos@ringieraxelspringer.hu'),
(142, 'Stammberger.Kinga', 'Koszó-Stammberger Kinga', 'RAS Magyarország Kft.', 'kinga.koszo@ringieraxelspringer.hu'),
(143, 'Szoke.Peter', 'Szőke Péter', 'RAS Magyarország Kft.', 'peter.szoke@ringieraxelspringer.hu'),
(144, 'Erdei.Viktoria', 'Erdei Viktória', 'RAS Magyarország Kft.', 'viktoria.erdei@ringieraxelspringer.hu'),
(145, 'Kortvelyesi.Andrea', 'Körtvélyesi Andrea', 'RAS Magyarország Kft.', 'andrea.kortvelyesi@ringieraxelspringer.hu'),
(146, 'Csabai.Gabor', 'Csabai Gábor', 'RAS-NYOMDA Nyomdaipari Kft.', 'gabor.csabai@ringieraxelspringer.hu'),
(147, 'szilady.raktar', 'Szilády raktár', 'RAS-NYOMDA Nyomdaipari Kft.', 'szilady.raktar@ringieraxelspringer.hu'),
(148, 'Hirdetes.Gyakornok', 'Hirdetés Gyakornok', 'AS-B Kft.', 'hirdetes.gyakornok@raspartner.hu'),
(149, 'Janko.Zita', 'Jankó Zita', 'AS-B Kft.', 'zita.janko@raspartner.hu'),
(150, 'Fekete.Szilvia', 'Fekete Szilvia', 'RAS Magyarország Kft.', 'szilvia.fekete@ringieraxelspringer.hu'),
(151, 'Tajti.Zsuzsanna', 'Tajti Zsuzsanna', 'RAS Magyarország Kft.', 'zsuzsa.tajti@ringieraxelspringer.hu'),
(152, 'Herczku.Beatrix', 'Herczku Beatrix', 'AS-B Kft.', 'beatrix.herczku@raspartner.hu'),
(153, 'Helmeczi.Szabolcsne', 'Helmeczi Szabolcsné', 'RAS Magyarország Kft.', 'szabolcsne.helmeczi@ringieraxelspringer.hu'),
(154, 'Nemeth.Maria', 'Németh Mária', 'RAS Magyarország Kft.', 'maria.nemeth@ringieraxelspringer.hu'),
(155, 'Nagy.Franciska', 'Nagy Franciska', 'RAS Magyarország Kft.', 'franciska.nagy@ringieraxelspringer.hu'),
(156, 'Horvath.Gergely', 'Horváth Gergely', 'RAS Magyarország Kft.', 'gergely.horvath@ringieraxelspringer.hu'),
(157, 'berenyi.zsofia', 'Berényi Zsófia', 'RAS Magyarország Kft.', 'zsofia.berenyi@ringieraxelspringer.hu'),
(158, 'marosfalvi.eva', 'Marosfalvi Éva', 'RAS Magyarország Kft.', 'eva.marosfalvi@ringieraxelspringer.hu'),
(159, 'Torzsa.Noemi', 'Torzsa Noémi', 'RAS Magyarország Kft.', 'noemi.torzsa@ringieraxelspringer.hu'),
(160, 'Szkiba.Irina', 'Szkiba Irina', 'AS-B Kft.', 'irina.szkiba@raspartner.hu'),
(161, 'Magan.Sarolta', 'Magán Sarolta', 'HarperCollins Magyarország Kft.', 'sarolta.magan@harpercollins.hu'),
(162, 'Nemeth.Andrea', 'Németh Andrea', 'RAS Magyarország Kft.', 'andrea.nemeth@ringieraxelspringer.hu'),
(163, 'Schubert.Andrea', 'Eisrichné Schubert Andrea', 'RAS Magyarország Kft.', 'andrea.schubert@ringieraxelspringer.hu'),
(164, 'sipos.eszter', 'Sipos Eszter', 'RAS Magyarország Kft.', 'eszter.sipos@ringieraxelspringer.hu'),
(165, 'detroi.krisztina', 'Detrői Krisztina', 'RAS Magyarország Kft.', 'krisztina.detroi@ringieraxelspringer.hu'),
(166, 'steiner.anna', 'Steiner Anna', 'RAS Magyarország Kft.', 'anna.steiner@ringieraxelspringer.hu'),
(167, 'Gaal.Zoltan', 'Gaál Zoltán István', 'Blikk Kft.', 'zoltan.gaal@blikk.hu'),
(168, 'Halas.Zoltan', 'Halas Zoltán', 'Blikk Kft.', 'zoltan.halas@blikk.hu'),
(169, 'Hacker.Tamas', 'Hacker Tamás', 'Blikk Kft.', 'tamas.hacker@blikk.hu'),
(170, 'Goronne.Margit', 'Goron Margó', 'Blikk Kft.', 'margit.goron@blikk.hu'),
(171, 'Farkas.Sandor', 'Farkas Sándor', 'Blikk Kft.', 'sandor.farkas@blikk.hu'),
(172, 'Szep.Zoltan', 'Szép Zoltán', 'Blikk Kft.', 'zoltan.szep@blikk.hu'),
(173, 'hasko.zsolt', 'Haskó Zsolt', 'Blikk Kft.', 'zsolt.hasko@blikk.hu'),
(174, 'vajta.zoltan', 'Vajta Zoltán', 'Blikk Kft.', 'zoltan.vajta@blikk.hu'),
(175, 'jambor.julianna', 'Jámbor Julianna', 'RAS Magyarország Kft.', 'julianna.jambor@ringieraxelspringer.hu'),
(176, 'pozsonyi.zita', 'Pozsonyi Zita', 'Blikk Kft.', 'zita.pozsonyi@blikk.hu'),
(177, 'Szirmay.David', 'Szirmay Dávid', 'Blikk Kft.', 'david.szirmay@blikk.hu'),
(178, 'Isza.Ferenc', 'Isza Ferenc', 'Blikk Kft.', 'ferenc.isza@blikk.hu'),
(179, 'Grnak.Laszlo', 'Grnák László', 'Blikk Kft.', 'laszlo.grnak@blikk.hu'),
(180, 'Fuszek.Gabor', 'Fuszek Gábor', 'Blikk Kft.', 'gabor.fuszek@blikk.hu'),
(181, 'gyori.laszlo', 'Győri László', 'Blikk Kft.', 'laszlo.gyori@blikk.hu'),
(182, 'Fekete.Lajos', 'Fekete Lajos', 'Blikk Kft.', 'lajos.fekete@blikk.hu'),
(183, 'bitto.akos', 'Bittó Ákos', 'Blikk Kft.', 'akos.bitto@blikk.hu'),
(184, 'csanda.gyula', 'Csanda Gyula', 'Blikk Kft.', 'gyula.csanda@blikk.hu'),
(185, 'csillag.timea', 'Csillag Tímea', 'Blikk Kft.', 'timea.csillag@blikk.hu'),
(186, 'csizmadia.adam', 'Csizmadia Ádám', 'Blikk Kft.', 'adam.csizmadia@blikk.hu'),
(187, 'kozak.daniel', 'Dr. Kozák Dániel', 'Blikk Kft.', 'daniel.kozak@blikk.hu'),
(188, 'fekete.attila', 'Fekete Attila', 'Blikk Kft.', 'attila.fekete@blikk.hu'),
(189, 'fogl.attila', 'Fogl Attila', 'Blikk Kft.', 'attila.fogl@blikk.hu'),
(190, 'gedei.norbert', 'Gedei Norbert', 'Blikk Kft.', 'norbert.gedei@blikk.hu'),
(191, 'gordos.robert', 'Gordos Róbert', 'Blikk Kft.', 'robert.gordos@blikk.hu'),
(192, 'halmos.szilvia', 'Halmos Ferencné', 'Blikk Kft.', 'szilvia.halmos@blikk.hu'),
(193, 'harnos.zsuzsanna', 'Harnos Zsuzsanna', 'Blikk Kft.', 'zsuzsanna.harnos@blikk.hu'),
(194, 'hollo.csaba', 'Holló Csaba', 'Blikk Kft.', 'csaba.hollo@blikk.hu'),
(195, 'jaray.eszter', 'Járay Eszter', 'RAS Magyarország Kft.', 'eszter.jaray@ringieraxelspringer.hu'),
(196, 'meszaros.istvan', 'Mészáros István', 'Blikk Kft.', 'istvan.meszaros@blikk.hu'),
(197, 'rigo.zsuzsa', 'Rigó Zsuzsa', 'Blikk Kft.', 'zsuzsa.rigo@blikk.hu'),
(198, 'nagy.erika', 'Kiss Erika', 'Blikk Kft.', 'erika.kiss@blikk.hu'),
(199, 'nemeth.attila', 'Németh Attila', 'Blikk Kft.', 'attila.nemeth@blikk.hu'),
(200, 'nyiri.gergely', 'Nyíri Gergely', 'Blikk Kft.', 'gergely.nyiri@blikk.hu'),
(201, 'papp.ferenc', 'Papp Ferenc', 'Blikk Kft.', 'ferenc.papp@blikk.hu'),
(202, 'pardi.magdolna', 'Pardi Magdolna', 'Blikk Kft.', 'magdolna.pardi@blikk.hu'),
(203, 'paulin.bela', 'Paulin Béla', 'Blikk Kft.', 'bela.paulin@blikk.hu'),
(204, 'palszabo.zoltan', 'Pálszabó Zoltán', 'Blikk Kft.', 'zoltan.palszabo@blikk.hu'),
(205, 'sera.tamas', 'Séra Tamás', 'Blikk Kft.', 'tamas.sera@blikk.hu'),
(206, 'laszlo.julianna', 'László Juli', 'Blikk Kft.', 'julianna.laszlo@blikk.hu'),
(207, 'szabadfi.monika', 'Szabadfi Mónika', 'Blikk Kft.', 'monika.szabadfi@blikk.hu'),
(208, 'szabo.david', 'Szabó Dávid', 'Blikk Kft.', 'david.szabo@blikk.hu'),
(209, 'szabo.endre', 'Szabó Árpád', 'Blikk Kft.', 'endre.szabo@blikk.hu'),
(210, 'szarka.judit', 'Szarka Judit', 'Blikk Kft.', 'judit.szarka@blikk.hu'),
(211, 'szaraz.peter', 'Száraz Péter', 'Blikk Kft.', 'peter.szaraz@blikk.hu'),
(212, 'tibay.gabor', 'Tibay Gábor', 'Blikk Kft.', 'gabor.tibay@blikk.hu'),
(213, 'varhelyi.zoltan', 'Várhelyi Zoltán', 'Blikk Kft.', 'zoltan.varhelyi@blikk.hu'),
(214, 'vizi.gyongyi', 'Vizi Gyöngyi Mária', 'Blikk Kft.', 'gyongyi.vizi@blikk.hu'),
(215, 'Pavelkovits.Petra', 'Pavelkovits Petra', 'Blikk Kft.', 'petra.pavelkovits@blikk.hu'),
(216, 'Blikk.foto1', 'Blikk fotó 1', 'Blikk Kft.', 'blikkfoto1@blikk.hu'),
(217, 'Molnar2.Gyongyi', 'Molnár Gyöngyi', 'RAS Magyarország Kft.', 'gyongyi.molnar2@ringieraxelspringer.hu'),
(218, 'balogh.gyula', 'Balogh Gyula', 'RAS Magyarország Kft.', 'gyula.balogh@ringieraxelspringer.hu'),
(219, 'Bajko.Panka', 'Bajkó Panka', 'Blikk Kft.', 'panka.bajko@blikk.hu'),
(220, 'Blikkhugyakornok1', 'BlikkhuGyakornok1', 'Blikk Kft.', 'blikkhugyakornok1@blikk.hu'),
(221, 'Savrnoh.Viktoria', 'Savrnoh Viktória', 'MEGA MOVIE Kft.', 'viktoria.savrnoh@raspartner.hu'),
(222, 'Kormendi.Richard', 'Körmendi Richárd', 'RAS Magyarország Kft.', 'richard.kormendi@ringieraxelspringer.hu'),
(223, 'Fodor.Gabor', 'Fodor Gábor', 'RAS Magyarország Kft.', 'gabor.fodor@ringieraxelspringer.hu'),
(224, 'bizalom', 'Profession Bizalom', 'Profession.hu Kft.', 'bizalom@profession.hu'),
(225, 'adam.bozsoki', 'Bozsoki Ádám', 'Profession.hu Kft.', 'adam.bozsoki@profession.hu'),
(226, 'adam.krajcs', 'Krajcs Ádám', 'Profession.hu Kft.', 'adam.krajcs@profession.hu'),
(227, 'alexandra.doczi', 'Dóczi Alexandra', 'Profession.hu Kft.', 'alexandra.doczi@profession.hu'),
(228, 'am.kovacs', 'Kovács András Márció', 'profession.hu Kft.', 'andras.kovacs@profession.hu'),
(229, 'ambassador', 'Profession Ambassador', 'Profession.hu Kft.', 'ambassador@profession.hu'),
(230, 'anett.kovacs', 'Kovács Anett', 'Profession.hu Kft.', 'anett.kovacs@profession.hu'),
(231, 'aniko.batka', 'Batka Anikó', 'Profession.hu Kft.', 'aniko.batka@profession.hu'),
(232, 'anna.fuglinszky', 'Fuglinszky Anna', 'Profession.hu Kft.', 'anna.fuglinszky@profession.hu'),
(233, 'anna.kadar', 'Kádár Anna', 'Profession.hu Kft.', 'anna.kadar@profession.hu'),
(234, 'annamaria.toth', 'Tóth Annamária', 'profession.hu Kft.', 'annamaria.toth@profession.hu'),
(235, 'attila.kallai', 'Kállai Attila', 'Profession.hu Kft.', 'attila.kallai@profession.hu'),
(236, 'ba.horvath', 'Horváth Balázs', 'profession.hu Kft.', 'balazs.horvath@profession.hu'),
(237, 'balazs.horvath', 'Horváth Balázs privát', 'profession.hu Kft.', 'ba.horvath@profession.hu'),
(238, 'balazs.simon', 'Simon Balázs', 'profession.hu Kft.', 'balazs.simon@profession.hu'),
(239, 'balazs.varga', 'Varga Balázs', 'Profession.hu Kft.', 'balazs.varga@profession.hu'),
(240, 'barbara.lombos', 'Lombos Barbara', 'Profession.hu Kft.', 'barbara.lombos@profession.hu'),
(241, 'cv_profession', 'cv_profession', 'Profession.hu Kft.', 'cv_profession@profession.hu'),
(242, 'dalma.krecz', 'Krecz Dalma', 'Profession.hu Kft.', 'dalma.krecz@profession.hu'),
(243, 'david.sinko', 'Sinkó Dávid', 'Profession.hu Kft.', 'david.sinko@profession.hu'),
(244, 'dispatcher.probos', 'Probos Dispatcher', 'Profession.hu Kft.', 'dispatcher.probos@profession.hu'),
(245, 'dominika.pataki', 'Pataki Dominika', 'profession.hu Kft.', 'dominika.pataki@profession.hu'),
(246, 'dora.gulyas', 'Hidvégi Gulyás Dóra', 'Profession.hu Kft.', 'dora.gulyas@profession.hu'),
(247, 'dora.szmolenszky', 'Lénárt Dóra', 'Profession.hu Kft.', 'dora.lenart@profession.hu'),
(248, 'dorottya.agotai', 'Szander-Ágotai Dorottya', 'Profession.hu Kft.', 'dorottya.agotai@profession.hu'),
(249, 'e.csala', 'Csala Éva', 'Profession.hu Kft.', 'eva.csala@profession.hu'),
(250, 'eszter.pajkos', 'Pajkos Eszter', 'profession.hu Kft.', 'eszter.pajkos@profession.hu'),
(251, 'eszamla_profession', 'Eszámla Profession', 'Profession.hu Kft.', 'eszamla_profession@profession.hu'),
(252, 'eva.bakondi', 'Bakondi Éva', 'Profession.hu Kft.', 'eva.bakondi@profession.hu'),
(253, 'eva.kecskes', 'Kecskés Éva', 'Profession.hu Kft.', 'eva.kecskes@profession.hu'),
(254, 'eva.wrobel', 'Wrobel Éva', 'Profession.hu Kft.', 'eva.wrobel@profession.hu'),
(255, 'evelin.majoros', 'Majoros Evelin', 'Profession.hu Kft.', 'evelin.majoros@profession.hu'),
(256, 'Gabriella.Polyak', 'Polyák Gabriella', 'profession.hu Kft.', 'gabriella.polyak@profession.hu'),
(257, 'gergely.boros', 'Boros Gergely', 'Profession.hu Kft.', 'gergely.boros@profession.hu'),
(258, 'gyorgy.sipiczki', 'Sipiczki György Dávid', 'Profession.hu Kft.', 'gyorgy.sipiczki@profession.hu'),
(259, 'hirdetes.probos', 'Probos Hirdetés', 'Profession.hu Kft.', 'hirdetes.probos@profession.hu'),
(260, 'ibolya.laczko', 'Laczkó-Angi Ibolya', 'Profession.hu Kft.', 'ibolya.laczko@profession.hu'),
(261, 'imola.okanyi', 'Okányi Imola', 'Profession.hu Kft.', 'imola.okanyi@profession.hu'),
(262, 'imola.solymosi', 'Solymosi Imola', 'Profession.hu Kft.', 'imola.solymosi@profession.hu'),
(263, 'imre.tuzes', 'Tüzes Imre', 'Profession.hu Kft.', 'imre.tuzes@profession.hu'),
(264, 'istvan.martis', 'Martis István Péter', 'Profession.hu Kft.', 'istvan.martis@profession.hu'),
(265, 'judit.kovesi', 'Herzogné Kövesi Judit', 'Profession.hu Kft.', 'judit.kovesi@profession.hu'),
(266, 'k.varga', 'Varga Krisztina', 'Sanoma Media Budapezt Zrt.', 'krisztina.varga@profession.hu'),
(267, 'k.varga.tanacsado', 'Profession Varga Kriszta', 'Profession.hu Kft.', 'krisztina.varga.tanacsado@profession.hu'),
(268, 'katalin.roman', 'Román Katalin', 'Profession.hu Kft.', 'katalin.roman@profession.hu'),
(269, 'kreativ', 'Profession Kreatív Megoldások', 'Profession.hu Kft.', 'kreativ@profession.hu'),
(270, 'krisztian.zsedely', 'Zsédely Krisztián', 'Profession.hu Kft.', 'krisztian.zsedely@profession.hu'),
(271, 'krisztina.fogas', 'Fogas Krisztina', 'Profession.hu Kft.', 'krisztina.fogas@profession.hu'),
(272, 'laczko.ibolya', 'Laczkó-Angi Ibolya Noémi', 'Profession.hu Kft.', 'laczko.ibolya@profession.hu'),
(273, 'laszlo.kuntar', 'Kuntár László Balázs', 'Profession.hu Kft.', 'laszlo.kuntar@profession.hu'),
(274, 'lili.gorocs', 'Göröcs Lili Melinda', 'Profession.hu Kft.', 'lili.gorocs@profession.hu'),
(275, 'maria.bodnar', 'Bodnár Mária', 'Profession.hu Kft.', 'maria.bodnar@profession.hu'),
(276, 'melinda.major', 'Major Melinda', 'Profession.hu Kft.', 'melinda.major@profession.hu'),
(277, 'mirabella.csomor', 'Csomor Mirabella', 'Sanoma Media Budapezt Zrt.', 'mirabella.csomor@profession.hu'),
(278, 'mistake prof', 'mistake prof', 'Profession.hu Kft.', 'mistake@profession.hu'),
(279, 'napiinfo', 'Napi Info', 'Profession.hu Kft.', 'napiinfo@profession.hu'),
(280, 'nikoletta.szigeti', 'Szigeti Nikoletta', 'Profession.hu Kft.', 'nikoletta.szigeti@profession.hu'),
(281, 'norbert.farkas', 'Farkas Norbert', 'Profession.hu Kft.', 'norbert.farkas@profession.hu'),
(282, 'orsolya.bacskai', 'Bácskai Orsolya', 'Profession.hu Kft.', 'orsolya.bacskai@profession.hu'),
(283, 'orsolya.nagy', 'Nagy Orsolya', 'Profession.hu Kft.', 'orsolya.nagy@profession.hu'),
(284, 'p.makay', 'Makay Péter', 'Profession.hu Kft.', 'peter.makay@profession.hu'),
(285, 'peter.kelemen', 'Kelemen Péter', 'Profession.hu Kft.', 'peter.kelemen@profession.hu'),
(286, 'peter.makay', 'Makay Péter privát', 'Profession.hu Kft.', 'p.makay@profession.hu'),
(287, 'petra.szanto', 'Szántó Petra', 'profession.hu Kft.', 'petra.szanto@profession.hu'),
(288, 'prof.karrier', 'Profession Karriertanácsadás', 'Profession.hu Kft.', 'karriertanacsadas@profession.hu'),
(289, 'prof.konferencia', 'Profession Konferencia', 'Profession.hu Kft.', 'konferencia@profession.hu'),
(290, 'prof.penzugy', 'Profession Pénzügy', 'Profession.hu Kft.', 'penzugy@profession.hu'),
(291, 'prof.szamlaertesites', 'Profession.hu Számlaértesítés', 'Profession.hu Kft.', 'szamlaertesites@profession.hu'),
(292, 'profession.behajto', 'Profession.hu Behajtó', 'Profession.hu Kft.', 'behajto@profession.hu'),
(293, 'profession.nyeremeny', 'Profession Nyereményjáték', 'Profession.hu Kft.', 'profession.nyeremeny@profession.hu'),
(294, 'profession.szakerto', 'Profession Szakértő', 'Profession.hu Kft.', 'szakerto@profession.hu'),
(295, 'renata.szauer', 'Szauer Renáta', 'Profession.hu Kft.', 'renata.szauer@profession.hu'),
(296, 'rita.solyom', 'Sólyom Rita', 'Profession.hu Kft.', 'rita.solyom@profession.hu'),
(297, 'roland.botlik', 'Botlik Roland', 'Profession.hu Kft', 'roland.botlik@profession.hu'),
(298, 'sales.probos', 'Probos Sales', 'Central Médiacsoport Zrt.', 'sales.probos@profession.hu'),
(299, 'salesmgr.probos', 'Probos Salesmgr', 'Central Médiacsoport Zrt.', 'salesmgr.probos@profession.hu'),
(300, 'sandor.meszar', 'Mészár Sándor', 'Profession.hu Kft.', 'sandor.meszar@profession.hu'),
(301, 'sandor.rago', 'Ragó Sándor', 'Profession.hu Kft.', 'sandor.rago@profession.hu'),
(302, 'tamas.kiss', 'Kiss Tamás', 'Profession.hu Kft.', 'tamas.kiss@profession.hu'),
(303, 'timea.hujber', 'Hujber Tímea', 'Profession.hu Kft.', 'timea.hujber@profession.hu'),
(304, 'veronika.pisztrai', 'Pisztrai Veronika', 'Profession.hu Kft.', 'veronika.pisztrai@profession.hu'),
(305, 'viktor.vido', 'Vidó Viktor', 'Profession.hu Kft.', 'viktor.vido@profession.hu'),
(306, 'visszahivas', 'Profession Visszahívás', 'Profession.hu Kft.', 'visszahivas@profession.hu'),
(307, 'z.vegh', 'Végh Zoltán  privát', 'profession.hu Kft.', 'z.vegh@profession.hu'),
(308, 'zsofia.berenyi', 'Berényi Zsófia', 'Profession.hu Kft.', 'zsofia.berenyi@profession.hu'),
(309, 'zsofia.petz', 'Petz Zsófia', 'profession.hu Kft.', 'zsofia.petz@profession.hu'),
(310, 'zsuzsa.borbely', 'Borbély Zsuzsanna', 'Profession.hu Kft.', 'zsuzsa.borbely@profession.hu'),
(311, 'jobadimport', 'profession jobadimport', 'Profession.hu Kft.', 'jobadimport@profession.hu'),
(312, 'Blikk.Gyakornok2', 'Blikk Gyakornok2', 'Blikk Kft.', 'Blikkgyakornok2@blikk.hu'),
(313, 'peter.fajt', 'Fajt Péter', 'profession.hu Kft.', 'peter.fajt@profession.hu'),
(314, 'Bajcsy.Marta', 'Bajcsy Márta', 'RAS Magyarország Kft.', 'marta.bajcsy@ringieraxelspringer.hu'),
(315, 'Gerentser.Imre', 'Gerentsér Imre', 'RAS Magyarország Kft.', 'imre.gerentser@ringieraxelspringer.hu'),
(316, 'Horakne.Bernadett', 'Horákné Szarka Bernadett', 'RAS Magyarország Kft.', 'bernadett.szarka@raspartner.hu'),
(317, 'dezso.katalin', 'Dezső Katalin', 'RAS Magyarország Kft.', 'katalin.dezso@ringieraxelspringer.hu'),
(318, 'Blikk.Gyakornok4', 'Blikk Gyakornok4', 'Blikk Kft.', 'blikkgyakornok4@blikk.hu'),
(319, 'Kulkov.Orsolya', 'Kulkov Orsolya', 'RAS Magyarország Kft.', 'orsolya.kulkov@ringieraxelspringer.hu'),
(320, 'weber.zsolt', 'Weber Zsolt', 'Blikk Kft.', 'zsolt.weber@blikk.hu'),
(321, 'vagi.bence', 'Vági Bence', 'Blikk Kft.', 'bence.vagi@blikk.hu'),
(322, 'Aniko.Dudas', 'Dudás Anikó', 'Profession.hu Kft.', 'aniko.dudas@profession.hu'),
(323, 'Tumpek.Imre', 'Tumpek Imre', 'Blikk Kft.', 'imre.tumpek@blikk.hu'),
(324, 'Szonyi.Beata', 'Szőnyi Beáta', 'RAS Magyarország Kft.', 'beata.szonyi@ringieraxelspringer.hu'),
(325, 'adam.varga', 'Varga Ádám', 'Profession.hu Kft.', 'adam.varga@profession.hu'),
(326, 'Blikkhugyakornok4', 'Blikkhu Gyakornok 4', 'Blikk Kft.', 'blikkhugyakornok4@gmail.com'),
(327, 'Feher.Andrea', 'Fehér Andrea', 'RAS Magyarország Kft.', 'andrea.feher@ringieraxelspringer.hu'),
(328, 'Blikkhugyakornok6', 'Blikkhu Gyakornok 6', 'Blikk Kft.', 'blikkhugyakornok6@blikk.hu'),
(329, 'Rejtvenylapok.Kozos', 'Rejtvénylapok Közös', NULL, 'rejtvenylapok.kulsos@raspartner.hu'),
(330, 'Tamara.Speiser', 'Speiser Tamara', 'profession.hu Kft.', 'tamara.speiser@profession.hu'),
(331, 'Katinka.Vajda', 'Vajda Katinka', 'profession.hu kft.', 'katinka.vajda@profession.hu'),
(332, 'Zsofia.Varga', 'Varga Zsófia', 'profession.hu Kft', 'zsofia.varga@profession.hu'),
(333, 'Andrea.Paulovics', 'Paulovics Andrea', 'profession.hu Kft.', 'andrea.paulovics@profession.hu'),
(334, 'Petra.Zsoldos', 'Zsoldos Petra', 'profession.hu Kft.', 'petra.zsoldos@profession.hu'),
(335, 'Eleonora.Balogh', 'Balogh Eleonóra', 'profession.hu Kft.', 'eleonora.balogh@profession.hu'),
(336, 'Ladanyi.Nikoletta', 'Ladányi Nikoletta', 'RAS Magyarország Kft.', 'nikoletta.ladanyi@ringieraxelspringer.hu'),
(337, 'Csabai.Alexandra', 'Csabai Alexandra', 'RAS Magyarország Kft.', 'alexandra.csabai@ringieraxelspringer.hu'),
(338, 'erzsebet.door', 'Doór Erzsébet', 'profession.hu Kft.', 'erzsebet.door@profession.hu'),
(339, 'Nep.Henrietta', 'Nép Henrietta', 'RAS Magyarország Kft.', 'henrietta.nep@ringieraxelspringer.hu'),
(340, 'Kalasz.Istvan', 'Kalász István', 'profession.hu Kft.', 'istvan.kalasz@profession.hu'),
(341, 'zsolt.fodor', 'Fodor Zsolt', 'Profession.hu Kft.', 'zsolt.fodor@profession.hu'),
(342, 'judit.offenbecker', 'Offenbecker Judit', 'profession.hu Kft.', 'judit.offenbecker@profession.hu'),
(343, 'Rona.Katalin', 'Róna Katalin', 'Gyapay Bt.', 'katalin.rona@raspartner.hu'),
(344, 'blanka.dencso', 'Páthy-Dencső Blanka', 'profession.hu Kft.', 'blanka.dencso@profession.hu'),
(345, 'Szokol.Martin', 'Szokol Martin', 'RAS Magyarország Kft.', 'martin.szokol@ringieraxelspringer.hu'),
(346, 'Kocsis.Zsuzsanna', 'Kocsis Zsuzsanna', 'Blikk Kft.', 'zsuzsa.kocsis@blikk.hu'),
(347, 'Dirner.Zsuzsanna', 'Dirner Zsuzsanna', 'RAS Magyarország Kft.', 'zsuzsanna.dirner@ringieraxelspringer.hu'),
(348, 'Okanyi.Imola', 'Okányi Imola', 'profession.hu Kft.', 'imola.okanyi@profession.hu'),
(349, 'Leka.Timea', 'Léka Tímea', 'RAS Magyarország Kft.', 'timea.leka@ringieraxelspringer.hu'),
(350, 'monika.gubanyi', 'Gubányi Mónika', NULL, 'monika.gubanyi@profession.hu'),
(351, 't265', '265-Sonkád-Profession', 'Profession.hu Kft.', 't265@profession.hu'),
(352, 'boglarka.nyitrai', 'Nyitrai Boglárka', 'profession.hu Kft.', 'boglarka.nyitrai@profession.hu'),
(353, 'MSMEODUser', 'MSMEODUser', NULL, 'MSMEODUser@as.local'),
(354, 'Pecskai.Istvan', 'Pécskai István', 'Blikk Kft.', 'istvan.pecskai@blikk.hu'),
(355, 'Lovanyi.Kata', 'Loványi Kata', 'RAS Magyarország Kft.', 'kata.lovanyi@ringieraxelspringer.hu'),
(356, 'rassupport', 'RASsupport', 'tesztcomp', 'RASsupport@profession.hu'),
(357, 'HealthMailbox7c9b1be', 'HealthMailbox-BP-MAIL2-NRML2DB', NULL, 'HealthMailbox7c9b1bec315e40758fbd791751490a21@as.local'),
(358, 'Nagy.Flora', 'Nagy Flóra', 'Blikk Kft.', 'flora.nagy@blikk.hu'),
(359, 'HealthMailboxf1b9ce5', 'HealthMailbox-BP-MAIL1-NRML2DB', NULL, 'HealthMailboxf1b9ce5558864d8f95f2c709e5c529b6@as.local'),
(360, 'proboshirdetes.test', 'proboshirdetes.test', 'Profession.hu Kft.', 'proboshirdetes.test@profession.hu'),
(361, 'diak.iroda', 'Diák iroda Profession', 'Profession.hu Kft.', 'diak.iroda@profession.hu'),
(362, 'eszamla.prof', 'E-Számla Profession', 'Profession.hu Kft.', 'e-szamla@profession.hu'),
(363, 'hirlevel', 'Profession Hírlevél', 'Profession.hu Kft.', 'hirlevel@profession.hu'),
(364, 'hr.gyakornok', 'Profession HR gyakornok', 'Profession.hu Kft.', 'hr.gyakornok@profession.hu'),
(365, 'prof.regisztracio', 'Profession Regisztráció', 'Profession.hu Kft.', 'regisztracio@profession.hu'),
(366, 'profession.support', 'Profession Support', 'Profession.hu Kft.', 'support@profession.hu'),
(367, 'szarvaskend', 'Szarvaskend-Profession', 'Profession.hu Kft.', 'szarvaskend@profession.hu'),
(368, 'bosarkany', 'Bősárkány Profession', 'Profession.hu Kft.', 'borsarkany@profession.hu'),
(369, 'uppony', 'Uppony-Profession', 'Profession.hu Kft.', 'uppony@profession.hu'),
(370, 'e.pajkos', 'Pajkos Eszter privát', 'profession.hu Kft.', 'e.pajkos@profession.hu'),
(371, 'Galgoczi.Krisztina', 'Galgóczi Krisztina', 'profession.hu Kft.', 'krisztina.galgoczi@profession.hu'),
(372, 'ugyfel.prof', 'Profession Ügyfélszolgálat', 'Profession.hu Kft.', 'ugyfelszolgalat@profession.hu'),
(373, 'helyettesites', 'helyettesítés', 'profession.hu Kft', 'helyettesites@profession.hu'),
(374, 'Hellebrandt.Dora', 'Hellebrandt Dóra', 'RAS Magyarország Kft.', 'dora.hellebrandt@ringieraxelspringer.hu'),
(375, 'reka.racz', 'Rácz Réka', 'profession.hu Kft.', 'reka.racz@profession.hu'),
(376, 'hirdetesteszt.probos', 'Probos Hirdetes Teszt', NULL, 'hirdetesteszt@profession.hu'),
(377, 'Kontos.Dora', 'Köntös Dóra', 'Blikk Kft.', 'dora.kontos@blikk.hu'),
(378, 'Noilapok.Gyakornok', 'Nőilapok Gyakornok', 'RAS Magyarország Kft.', 'noilapok.gyakornok@raspartner.hu'),
(379, 'Blikk.gyakornok1', 'Blikk gyakornok1', 'Blikk Kft.', 'blikkgyakornok1@blikk.hu'),
(380, 'Forro.Gabor', 'Forró Gábor', 'RAS Magyarország Kft.', 'gabor.forro@ringieraxelspringer.hu'),
(381, 'Nemeth2.Eva', 'Németh Éva', 'Blikk Kft.', 'eva.nemeth@blikk.hu'),
(382, 'Braun.Csaba', 'Braun Csaba', 'Bril-Soft Bt.', 'csaba.braun@raspartner.hu'),
(383, 'Blikk.Gyakornok5', 'Blikk Gyakornok5', 'Blikk Kft.', 'blikkgyakornok5@blikk.hu'),
(384, 'Zsofia.Kiss', 'Kiss Zsófia', 'Profession.hu Kft.', 'zsofia.kiss@profession.hu'),
(385, 'Marta.Fulop', 'Fülöp Mária Márta', 'profession.hu Kft.', 'marta.fulop@profession.hu'),
(386, 'BlikkhuGyakornok8', 'Blikkhu Gyakornok8', 'Blikk Kft.', 'blikkhugyakornok8@blikk.hu'),
(387, 'hirdetesteszt2.probo', 'hirdetesteszt2.probos', NULL, 'hirdetesteszt2@profession.hu'),
(388, 'BlikkhuGyakornok10', 'Blikkhu Gyakornok10', 'Blikk Kft.', 'blikkhugyakornok10@blikk.hu'),
(389, 'BlikkhuGyakornok9', 'Blikkhu Gyakornok9', 'Blikk Kft.', 'blikkhugyakornok9@blikk.hu'),
(390, 'Ferenc.Havas', 'Havas Ferenc', 'profession.hu Kft.', 'Ferenc.Havas@profession.hu'),
(391, 'Eszter.Laki', 'Laki Eszter', 'Profession.hu Kft.', 'Eszter.Laki@profession.hu'),
(392, 'a.fuglinszky', 'Fuglinszky Anna privát', 'Profession.hu Kft.', 'a.fuglinszky@profession.hu'),
(393, 'k.roman', 'Román Katalin privát', 'Profession.hu Kft.', 'k.roman@profession.hu'),
(394, 'e.bakondi', 'Bakondi Éva privát', 'Profession.hu Kft.', 'e.bakondi@profession.hu'),
(395, 'p.kelemen', 'Kelemen Péter privát', 'Profession.hu Kft.', 'p.kelemen@profession.hu'),
(396, 'a.kallai', 'Kállai Attila privát', 'Profession.hu Kft.', 'a.kallai@profession.hu'),
(397, 'e.majoros', 'Majoros Evelin privát', 'Profession.hu Kft.', 'e.majoros@profession.hu'),
(398, 'r.racz', 'Rácz Réka privát', 'profession.hu Kft.', 'r.racz@profession.hu'),
(399, 'zs.berenyi', 'Berényi Zsófia privát', 'Profession.hu Kft.', 'zs.berenyi@profession.hu'),
(400, 'r.szauer', 'Szauer Renáta privát', 'Profession.hu Kft.', 'r.szauer@profession.hu'),
(401, 'i.solymosi', 'Solymosi Imola privát', 'Profession.hu Kft.', 'i.solymosi@profession.hu'),
(402, 'a.paulovics', 'Paulovics Andrea privát', 'profession.hu Kft.', 'a.paulovics@profession.hu'),
(403, 'i.okanyi', 'Okányi Imola privát', NULL, 'i.okanyi@profession.hu'),
(404, 'b.lombos', 'Lombos Barbara privát', 'profession.hu Kft.', 'b.lombos@profession.hu'),
(405, 'p.szanto', 'Szántó Petra privát', 'profession.hu Kft.', 'p.szanto@profession.hu'),
(406, 'fo.helyettesites', 'fo helyettesítés', 'Profession.hu Kft.', 'fo.helyettesites@profession.hu'),
(407, 'Kincses.Erika', 'Kincses Erika', 'Blikk Kft.', 'erika.kincses@blikk.hu'),
(408, 'nelli.kiripolszki', 'Kiripolszki Nelli', 'profession.hu Kft.', 'nelli.kiripolszki@profession.hu'),
(409, 'customerservice', 'customerservice Profession', 'Profession.hu Kft.', 'customerservice@profession.hu'),
(410, 'diak.profession', 'Diák Profession', 'Profession.hu Kft.', 'diak.profession@profession.hu'),
(411, 'Virag.Daniel', 'Virág Dániel', 'RAS Magyarország Kft.', 'daniel.virag@ringieraxelspringer.hu'),
(412, 'Tukacs.Tekla', 'Tukacs Tekla', 'Blikk Kft.', 'tekla.tukacs@blikk.hu'),
(413, 'Rakasz.Szilvia', 'Kovácsné Rákász Szilvia', 'RAS Magyarország Kft.', 'szilvia.rakasz@raspartner.hu'),
(414, 'marketing.profession', 'Marketing Profession', 'Profession.hu Kft.', 'marketing@profession.hu'),
(415, 'sendmail', 'Send Mail', NULL, 'noreply@profession.hu'),
(416, 'Noilapok.Gyakornok2', 'Nőilapok Gyakornok 2', 'RAS Magyarország Kft.', 'noilapok.gyakornok2@raspartner.hu'),
(417, 'Noilapok.Onlinegyak2', 'Nőilapok Onlinegyakornok 2', 'RAS Magyarország Kft.', 'noilapok.onlinegyakornok2@raspartner.hu'),
(418, 'Noilapok.Onlinegyak', 'Nőilapok Onlinegyakornok', 'RAS Magyarország Kft.', 'noilapok.onlinegyakornok@raspartner.hu'),
(419, 'Ferentzi.Andras', 'Ferentzi András', 'Blikk Kft.', 'andras.ferentzi@blikk.hu'),
(420, 'Szigeti.Monika', 'Ajkai-Szigeti Mónika Anikó', 'RAS Magyarország Kft.', 'monika.ajkai-szigeti@ringieraxelspringer.hu'),
(421, 'ibolya.szakaly', 'Szakály Ibolya', 'profession.hu Kft.', 'ibolya.szakaly@profession.hu'),
(422, 'hangposta', 'Profession Hangposta', 'Profession.hu Kft.', 'hangposta@profession.hu'),
(423, 'Obreczany.Eva', 'Obreczány Éva', 'Blikk Kft.', 'eva.obreczany@blikk.hu'),
(424, 'Lakat.Eszter', 'Lakat Eszter', 'Blikk Kft.', 'eszter.lakat@blikk.hu'),
(425, 'annamaria.gyori', 'Győri Annamária privát', 'profession.hu Kft.', 'an.gyori@profession.hu'),
(426, 'eszter.mikita', 'Mikita Eszter Dóra', 'profession.hu Kft.', 'eszter.mikita@profession.hu'),
(427, 'an.gyori', 'Győri Annamária', 'profession.hu Kft.', 'annamaria.gyori@profession.hu'),
(428, 'Taraszovics.Agnes', 'Taraszovics Ágnes', 'RAS Magyarország Kft.', 'agnes.taraszovics@ringieraxelspringer.hu'),
(429, 'zoltan.berkes', 'Berkes Zoltán', 'Berkes Zoltán e.v.', 'zoltan.berkes@profession.hu'),
(430, 'Herczku.Nora', 'Herczku Nóra', 'Blikk Kft.', 'nora.herczku@blikk.hu'),
(431, 'Kerekes.Csilla', 'Kerekes Csilla', 'RAS Magyarország Kft.', 'csilla.kerekes@ringieraxelspringer.hu'),
(432, 'adam.kovacs', 'Kovács Ádám', 'profession.hu Kft.', 'adam.kovacs@profession.hu'),
(433, 'topdeskuser', 'Topdesk User', 'Profession.hu Kft.', 'topdeskuser@as.local'),
(434, 'vivien.andavolgyi', 'Andavölgyi Vivien', 'profession.hu Kft.', 'vivien.andavolgyi@profession.hu'),
(435, 'marton.gombo', 'Gombó Márton', 'profession.hu Kft.', 'marton.gombo@profession.hu'),
(436, 'julia.hevesi', 'Hevesi Júlia', 'profession.hu Kft.', 'julia.hevesi@profession.hu'),
(437, 'Szrjeborni.Bianka', 'Szrjeborni Bianka Viktória', 'Blikk Kft.', 'bianka.szrjeborni@blikk.hu'),
(438, 'barbara.lengyel', 'Lengyel Barbara', 'profession.hu Kft.', 'barbara.lengyel@profession.hu'),
(439, 'diana.erdelyi', 'Erdélyi Diána', 'profession.hu Kft.', 'diana.erdelyi@profession.hu'),
(440, 'moderalas', 'Profession Moderálás', 'Profession.hu Kft.', 'moderalas@profession.hu'),
(441, 'Dittrich.Diana', 'Dittrich Diána', 'Damit Informatika Kft.', 'diana.dittrich@raspartner.hu'),
(442, 'kinga.kancsar', 'Kancsár Kinga', 'profession.hu Kft.', 'kinga.kancsar@profession.hu'),
(443, 'Balogh.Andras', 'Balogh András', 'Damit Informatika kft.', 'andras.balogh@raspartner.hu'),
(444, 'Brandl.Emil', 'Brandl Emil', 'Damit Informatika kft.', 'emil.brandl@raspartner.hu'),
(445, 'Antal.Mark', 'Antal Márk', 'Damit Informatika kft.', 'mark.antal@profession.hu'),
(446, 'Safar.Zoltan', 'Sáfár Zoltán', 'Damit Informatika kft.', 'zoltan.safar@raspartner.hu'),
(447, 'Kinka.Alexisz', 'Kinka Alexisz', 'Damit Informatika kft.', 'alexis.kinka@raspartner.hu'),
(448, 'renata.posta', 'Posta Renáta Krisztina', 'Posta Renáta Krisztina egyéni vállalkozó', 'renata.posta@profession.hu'),
(449, 'eszamla', 'TOPdesk E-számla', 'Profession.hu Kft.', 'eszamla@profession.hu'),
(450, 'elolegbekero', 'TOPdesk Előlegbekérő', 'Profession.hu Kft.', 'elolegbekero@profession.hu'),
(451, 'recovery', 'TOPdesk Recovery', 'Profession.hu Kft.', 'recovery@profession.hu'),
(452, 'notification.probos', 'Probos Notification', 'Profession.hu Kft.', 'notification.probos@profession.hu'),
(453, 'Lukacs.Gabor', 'Lukács Gábor', 'RAS Magyarország Kft.', 'gabor.lukacs@profession.hu'),
(454, 'Reubl.Istvan', 'Reubl István', 'RAS Magyarország Kft.', 'istvan.reubl@ringieraxelspringer.hu'),
(455, 'orsolya.torma', 'Torma Orsolya', 'Profession.hu Kft.', 'orsolya.torma@profession.hu'),
(456, 'ildiko.varnyu', 'Varnyu Ildikó', 'Profession.hu Kft.', 'ildiko.varnyu@profession.hu'),
(457, 'kraszny.attila', 'Kraszny Attila', NULL, 'attila.kraszny@rasparner.hu'),
(458, 'diana.klemencsics', 'Klemencsics Diána', 'Profession.hu Kft.', 'diana.klemencsics@profession.hu'),
(459, 'timea.viola', 'Viola Tímea', 'Profession.hu Kft.', 'timea.viola@profession.hu'),
(460, 'o.torma', 'Torma Orsolya privát', 'Profession.hu Kft.', 'o.torma@profession.hu'),
(461, 'i.varnyu', 'Varnyu Ildikó privát', 'Profession.hu Kft.', 'i.varnyu@profession.hu'),
(462, 'Szarvas.Zsolt', 'Szarvas Zsolt', 'Blikk Kft.', 'zsolt.szarvas@blikk.hu'),
(463, 'nikoletta.bella', 'Bella Nikoletta', 'Profession.hu Kft.', 'nikoletta.bella@profession.hu'),
(464, 'Harnisch.Kitti', 'Harnisch Kitti', 'Blikk Kft.', 'kitti.harnisch@blikk.hu'),
(465, 'Szauer.David', 'Szauer Dávid', 'Damit Informatika kft.', 'david.szauer@raspartner.hu'),
(466, 'webinar', 'Profession Webinárium', 'Profession.hu Kft.', 'webinar@profession.hu'),
(467, 'Rejtvenylapok.Tordel', 'Rejtvénylapok Tördelő', 'RAS Magyarország Kft.', 'rejtvenylapok.tordelo@raspartner.hu'),
(468, 'egyenlegkozlo', 'Egyenlegközlő', 'Profession.hu Kft.', 'egyenlegkozlo@profession.hu'),
(469, 'Hortobagyi.Julia', 'Hortobágyi Júlia', 'RAS Magyarország Kft.', 'julia.hortobagyi@ringieraxelspringer.hu'),
(470, 'Koczka.Eva', 'Koczka Éva', 'RAS Magyarország Kft.', 'eva.koczka@raspartner.hu'),
(471, 'bettina.bacsi', 'Bácsi Bettina', 'Profession.hu Kft.', 'bettina.bacsi@profession.hu'),
(472, 'iphone1', 'iphone 1', 'Profession.hu Kft.', 'iphone1@profession.hu'),
(473, 'ugyfelkapcsolat_bcp', 'ugyfelkapcsolat_bcp', 'Profession.hu Kft.', 'ugyfelkapcsolat_bcp@profession.hu'),
(474, 'customerobsession', 'customerobsession', 'Profession.hu Kft.', 'customerobsession@profession.hu'),
(475, 'puls.test', 'Puls Test', NULL, 'puls.test@ringieraxelspringer.hu'),
(476, 'judit.varga', 'Varga Judit', 'profession.hu Kft.', 'judit.varga@profession.hu'),
(477, 'eszter.pataky', 'Pataky Eszter', 'Profession.hu Kft.', 'eszter.pataky@profession.hu'),
(478, 'sandor.nagy', 'Nagy Sándor László', 'Profession.hu Kft.', 'sandor.laszlo.nagy@profession.hu'),
(479, 'katalin.molnar', 'Molnár Judit Katalin', 'Profession.hu Kft.', 'katalin.molnar@profession.hu'),
(480, 'orsolya.bakos', 'Bakos Orsolya Adrienn', 'Profession.hu Kft.', 'orsolya.bakos@profession.hu'),
(481, 'adrienn.hartmann', 'Hartmann Adrienn', 'Profession.hu Kft.', 'adrienn.hartmann@profession.hu'),
(482, 'Krusinszki.Jozsef', 'Krusinszki József', 'Blikk Kft.', 'jozsef.krusinszki@blikk.hu'),
(483, 'Pogonyi.Nora', 'Pogonyi Nóra', 'Blikk Kft.', 'nora.pogonyi@blikk.hu'),
(484, 'Mukics.Beata', 'Mukics Beáta', 'RAS Magyarország Kft.', 'beata.mukics@ringieraxelspringer.hu'),
(485, 'meszaros.ferenc', 'Mészáros Ferenc', 'DAMIT Informatika Kft.', 'ferenc.meszaros@raspartner.hu'),
(486, 'mohl.adam', 'Mohl Ádám', 'DAMIT Informatika Kft.', 'adam.mohl@raspartnert.hu'),
(487, 'allashirlevel_prof', 'Hirlevel Allas', 'Profession.hu Kft.', 'allashirlevel_prof@profession.hu'),
(488, 'sara.parrag', 'Parrag Sára', 'Profession.hu Kft.', 'sara.parrag@profession.hu'),
(489, 'klau.mattyasovszky', 'Mattyasovszky Klaudia', 'Profession.hu Kft.', 'klaudia.mattyasovszky@profession.hu'),
(490, 'berey.eszter', 'Berey Eszter', 'RAS Magyarország Kft.', 'eszter.berey@raspartner.hu'),
(491, 'Cserep.Tamas', 'Cserép Tamás', 'RAS Magyarország Kft.', 'tamas.cserep@ringieraxelspringer.hu'),
(492, 'Zieger.Milan', 'Zieger Milán', 'RAS Magyarország Kft.', 'milan.zieger@ringieraxelspringer.hu'),
(493, 'Btier.Noemi', 'B. Tier Noémi', 'RAS Magyarország Kft.', 'noemi.b.tier@ringieraxelspringer.hu'),
(494, 'jobmonitor', 'Jobmonitor', 'Profession.hu Kft.', 'jobmonitor@profession.hu'),
(495, 'munkaado.ugyfelkapu', 'Ügyfélkapu Munkaadó', 'Profession.hu Kft.', 'munkaado.ugyfelkapu@profession.hu'),
(496, 'usz.munkatarsaim', 'Munkatársaim Ügyfélszolgálat', 'Profession.hu Kft.', 'ugyfelszolgalat.munkatarsaim@as.local'),
(497, 'mv.ugyfelkapu', 'Ügyfélkapu Munkavállaló', 'Profession.hu Kft.', 'munkavallalo.ugyfelkapu@as.local'),
(498, 'budaiadm', 'Budai Tibor', 'AS-B Kft.', 'tibor.budai@raspartner.hu'),
(499, 'horvath.adam', 'Horváth Ádám', 'RAS Magyarország Kft.', 'adam.horvath@ringieraxelspringer.hu'),
(500, 'Csiki.Erika', 'Csíki Erika', 'RAS Magyarország Kft.', 'erika.csiki@ringieraxelspringer.hu'),
(501, 'kozari.szilvia', 'Kozári Szilvia', 'RAS Magyarország Kft.', 'szilvia.kozari@ringieraxelspringer.hu'),
(502, 'szabo.laszlo', 'Szabó László', 'RAS Magyarország Kft.', 'laszlo.szabo@ringieraxelspringer.hu'),
(503, 'ssc', 'Profession SSC', NULL, 'ssc@professionservices.hu'),
(504, 'finance', 'Profession Finance', NULL, 'finance@professionservices.hu'),
(505, 'it', 'Profession IT', NULL, 'it@professionservices.hu'),
(506, 'manufacturing', 'Profession Manufacturing', NULL, 'manufacturing@professionservices.hu'),
(507, 'professionadmin', 'Profession Admin', NULL, 'admin@professionservices.hu'),
(508, 'sales', 'Sales Professionservices', NULL, 'sales@professionservices.hu'),
(509, 'hr1', 'Profession HR', NULL, 'hr@professionservices.hu'),
(510, 'marketing', 'Profession Marketing', NULL, 'marketing@professionservices.hu'),
(511, 'Ferenczi.Fruzsina', 'Ferenczi Fruzsina', 'Blikk Kft.', 'fruzsina.ferenczi@blikk.hu'),
(512, 'timea.balazs', 'Balázs Tímea', 'Profession.hu Kft.', 'timea.balazs@profession.hu'),
(513, 'fruzsina.beke', 'Beke Fruzsina', 'Profession.hu Kft.', 'fruzsina.beke@profession.hu'),
(514, 'fanni.kovacs', 'Kovács Fanni Eszter', 'Profession.hu Kft.', 'fanni.kovacs@profession.hu'),
(515, 'csilla.kiraly', 'Király Csilla', 'Profession.hu Kft.', 'csilla.kiraly@profession.hu'),
(516, 'b.bacsi', 'Bácsi Bettina Privát', 'Profession.hu Kft.', 'b.bacsi@profession.hu'),
(517, 'fulop.anett', 'Fülöp Anett', 'Blikk Kft.', 'anett.fulop@blikk.hu'),
(518, 'kerek.ildiko', 'Kerek Ildikó', 'RAS Magyarország Kft.', 'ildiko.kerek@ringieraxelspringer.hu'),
(519, 'Berki.Lili', 'Berki Lili Emília', 'RAS Magyarország Kft.', 'lili.berki@ringieraxelspringer.hu'),
(520, 'Havasi.Virag', 'Havasi Virág', 'RAS Magyarország Kft.', 'virag.havasi@ringieraxelspringer.hu'),
(521, 'Bognar.Peter', 'Bognár Péter', 'RAS Magyarország Kft.', 'peter.bognar@ringieraxelspringer.hu'),
(522, 'csaba.moldovan', 'Moldován Csaba Zoltán', 'Profession.hu Kft.', 'csaba.moldovan@profession.hu'),
(523, 'ninetta.sala', 'Sala Ninetta', 'RAS Magyarország Kft.', 'ninetta.sala@ringieraxelspringer.hu'),
(524, 'veres.gabor', 'Veres Gábor', 'Blikk Kft.', 'gabor.veres@blikk.hu'),
(525, 'gaal.tamara', 'Gaál Tamara', 'Blikk Kft.', 'tamara.gaal@blikk.hu'),
(526, 'szakacs.andras', 'Szakács András', 'RAS Magyarország Kft.', 'andras.szakacs@ringieraxelspringer.hu'),
(527, 'Szira.Krisztina', 'Szira Krisztina', 'RAS Magyarország Kft.', 'krisztina.szira@ringieraxelspringer.hu'),
(528, 'nagy.melinda', 'Nagy Melinda', 'RAS Magyarország Kft.', 'melinda.nagy@ringieraxelspringer.hu'),
(529, 'dietrich.ilona', 'Dietrich Ilona', 'RAS Magyarország Kft.', 'ilona.dietrich@ringieraxelspringer.hu'),
(530, 'simon.izabella', 'Simon Izabella', 'RAS Magyarország Kft.', 'izabella.simon@ringieraxelspringer.hu'),
(531, 'attila.racz', 'Rácz Attila', 'Profession.hu Kft.', 'attila.racz@profession.hu'),
(532, 'hirdetesek.jm', 'Jobmonitor hirdetések Technikai fiók', 'Profession.hu Kft.', 'hirdetesek.jm@profession.hu'),
(533, 'allaskeresok.jm', 'Jobmonitor álláskeresők Technikai fiók', 'Profession.hu Kft.', 'allaskeresok.jm@profession.hu'),
(534, 'resan.alexandra', 'Resán Alexandra', 'RAS Magyarország Kft.', 'alexandra.resan@ringieraxelspringer.hu'),
(535, 'tihanyi.balazs', 'Tihanyi Balázs', 'RAS Magyarország kft.', 'balazs.tihanyi@ringieraxelspringer.hu'),
(536, 'horvath.fatima', 'Horváth Fatima', 'RAS Magyarország Kft.', 'fatima.horvath@ringieraxelspringer.hu'),
(537, 'muzsnyai.aniko', 'Muzsnyai Anikó', 'RAS-NYOMDA Nyomdaipari Kft.', 'aniko.muzsnyai@ringieraxelspringer.hu'),
(538, 'digital.ugyelet', 'Digital Ügyelet', 'RAS Magyarország Kft.', 'digitalugyelet@ras.hu'),
(539, 'roosz.anita', 'Roósz Anita', 'RAS Magyarország Kft.', 'anita.roosz@ringieraxelspringer.hu'),
(540, 'oktatas', 'Oktatás Profession', 'Profession.hu Kft.', 'oktatas@profession.hu'),
(541, 'richard.balogh', 'Balogh Richárd', 'Profession.hu Kft.', 'richard.balogh@profession.hu'),
(542, 'koszoru.csaba', 'Koszorú Csaba', 'RAS Magyarország Kft.', 'csaba.koszoru@ringieraxelspringer.hu'),
(543, 'eva.sziklas', 'Sziklás Éva', 'Profession.hu Kft.', 'eva.sziklas@profession.hu'),
(544, 'suto.vivien', 'Sütő Vivien', 'RAS Magyarország kft.', 'vivien.suto@ringieraxelspringer.hu'),
(545, 'anita.palfi', 'Pálfi Anita', 'Profession.hu Kft.', 'anita.palfi@profession.hu'),
(546, 'andras.matyasi', 'Mátyási András Jakab', 'Profession.hu Kft.', 'andras.matyasi@profession.hu'),
(547, 'eszter.varga', 'Varga Eszter', 'RAS Magyarország Kft.', 'eszter.varga@profession.hu'),
(548, 'eva.sziklasi', 'Sziklási Éva', 'Profession.hu Kft.', 'eva.sziklasi@profession.hu'),
(549, 'iphone2', 'Iphone2', NULL, 'iphone2@profession.hu'),
(550, 'valentin.ver', 'Vér Valentin', 'Profession.hu Kft.', 'valentin.ver@profession.hu'),
(551, 'gyorkos.laszlo', 'Györkös László', 'RAS Magyarország Kft.', 'laszlo.gyorkos@ringieraxelspringer.hu'),
(552, 'veeambackup', 'Technikai user Veeam', 'Profession.hu Kft.', 'veeambackup@profession.hu'),
(553, 'rendszeruzenetek', 'Rendszerüzenetek Ügyfélszolgálat', NULL, 'rendszeruzenetek@profession.hu'),
(554, 'dora.mikita', 'Mikita Eszter', 'Profession.hu Kft.', 'dora.mikita@profession.hu'),
(555, 'babos.kitti', 'Babos Kitti', 'RAS Magyarország kft.', 'kitti.babos@ringieraxelspringer.hu'),
(556, 'herceg.eva', 'Herceg Éva', 'RAS Magyarország Kft.', 'eva.herceg@ringieraxelspringer.hu'),
(557, 'petrenyi.jozsef', 'Petrényi József', 'Damit Informatika kft.', 'petrenyi.jozsef@damit.hu'),
(558, 'gal.tamas', 'Gál Tamás', 'Damit Informatika kft.', 'gal.tamas@damit.hu'),
(559, 'andrea.laszlo', 'László Andrea', 'Profession.hu Kft.', 'andrea.laszlo@profession.hu'),
(560, 'vegh.franciska', 'Végh Franciska', 'RAS Magyarország kft.', 'franciska.vegh@ringieraxelspringer.hu'),
(561, 'szabolcs.hovanecz', 'Hovanecz Szabolcs', 'Profession.hu Kft.', 'szabolcs.hovanecz@profession.hu'),
(562, 'szabo.gergely', 'Szabó Gergely', 'RAS Magyarország kft.', 'gergely.szabo@ringieraxelspringer.hu'),
(563, 'judit.farkas', 'Farkas Judit', 'Profession.hu Kft.', 'judit.farkas@profession.hu'),
(564, 'markos.viktor', 'Markos Viktor', 'RAS magyarország kft.', 'viktor.markos@ringieraxelspringer.hu'),
(565, 'dora.szilagyi', 'Szilágyi Dóra', 'Profession.hu Kft.', 'dora.szilagyi@profession.hu'),
(566, 'digitalis.gyakornok', 'Digitális.Gyakornok', 'RAS Magyarország Kft.', 'digitalis.gyakornok@raspartner.hu'),
(567, 'slemmer.adam', 'Slemmer Ádám', 'RAS Magyarország Kft.', 'adam.slemmer@ringieraxelspringer.hu'),
(568, 'bori.adam', 'Bori Ádám', 'RAS Magyarország Kft.', 'adam.bori@ringieraxelspringer.hu'),
(569, 'bela.kummer', 'Kummer Béla', 'Profession.hu Kft.', 'bela.kummer@profession.hu'),
(570, 'inbound', 'Profession Inbound', NULL, 'inbound@professionservices.hu'),
(571, 'marketing.gyakornok', 'marketing.gyakornok', 'RAS Magyarország kft.', 'marketing.gyakornok@raspartner.hu'),
(572, 'robert.ancsin', 'Ancsin Róbert János', 'Profession.hu Kft.', 'robert.ancsin@profession.hu'),
(573, 'erika.sipos', 'Sipos Erika', 'Profession.hu Kft.', 'erika.sipos@profession.hu'),
(574, 'gyorgyi.branizsa', 'Branizsa Györgyi', 'Profession.hu Kft.', 'gyorgyi.branizsa@profession.hu'),
(575, 'bernadette.bariz', 'Bariz Bernadette', 'Profession.hu Kft.', 'bernadette.bariz@profession.hu'),
(576, 'borbala.gergely', 'Gergely Borbála', 'Profession.hu Kft.', 'borbala.gergely@profession.hu'),
(577, 'hanna.staudt', 'Staudt Hanna', 'Profession.hu Kft.', 'hanna.staudt@profession.hu'),
(578, 'pereszlenyi.peter', 'Pereszlényi Péter', 'Blikk Kft.', 'peter.pereszlenyi@blikk.hu'),
(579, 'biro.eszter', 'Bíró Eszter', 'RAS Magyarország kft.', 'eszter.biro@ringieraxelspringer.hu'),
(580, 'sellei.noemi', 'Séllei Noémi', 'Blikk kft.', 'noemi.sellei@blikk.hu'),
(581, 'kollat.gabor', 'Kollát Gábor', 'RAS Magyarország Kft.', 'gabor.kollat@ringieraxelspringer.hu'),
(582, 'marketing.gyakornok2', 'marketing gyakornok2', 'RAS Magyarország kft.', 'marketing.gyakornok2@raspartner.hu'),
(583, 'szakal.reka', 'Szakál Réka', 'RAS Magyarország kft. - egyéni vállalkozó', 'reka.szakal@ringieraxelspringer.hu'),
(584, 'fruzsina.borokai', 'Borókai Fruzsina Borbála', 'Profession.hu Kft.', 'fruzsina.borokai@profession.hu'),
(585, 'f.borokai', 'Borókai Fruzsina Borbála Privát', NULL, 'f.borokai@profession.hu'),
(586, 'marta.kubola', 'Kubola Márta', 'profession.hu Kft.', 'marta.kubola@profession.hu'),
(587, 'd.hidvegi', 'Hidvégi Gulyás Dóra privát', 'Profession.hu Kft.', 'd.hidvegi@profession.hu'),
(588, 'molnar.gyongyi', 'Molnár Gyöngyi', 'RAS Magyarország kft.', 'gyongyi.molnar@ringieraxelspringer.hu'),
(589, 'akos.toth', 'Tóth Ákos Dávid', 'Profession.hu Kft.', 'akos.toth@profession.hu'),
(590, 'misley.katalin', 'Misley Katalin', 'RAS Magyarország Kft.', 'katalin.misley@ringieraxelspringer.hu'),
(591, 'seres.livia', 'Seres Lívia', 'RAS Magyarország kft.', 'livia.seres@ringieraxelspringer.hu'),
(592, 'csala.robert', 'Csala Róbert', 'RAS Magyarország kft.', 'robert.csala@ras-oander.com'),
(593, 'balazs.vida', 'Vida Balázs', 'Profession.hu Kft.', 'balazs.vida@profession.hu'),
(594, 'katymari.vanda', 'Katymári Vanda', 'RAS Magyarország Kft.', 'vanda.katymari@ringieraxelspringer.hu'),
(595, 'Kiss.Attila', 'Kiss Attila', 'RAS Magyarország Kft.', 'attila.kiss@ringieraxelspringer.hu'),
(596, 'osz.anita', 'Ősz Anita', 'Blikk Kft.', 'anita.osz@blikk.hu'),
(597, 'baksa.istvan', 'Baksa István', 'RAS Magyarország Kft.', 'istvan.baksa@ringieraxelspringer.hu'),
(598, 'logisztika', 'Logisztika Professionservices', NULL, 'logisztika@professionservices.hu'),
(599, 'helga.benyeda', 'Benyeda Helga', 'Profession.hu Kft.', 'helga.benyeda@profession.hu'),
(600, 'akos.sebok', 'Sebők Ákos Álmos', 'Profession.hu Kft.', 'almos.sebok@profession.hu'),
(601, 'piko.mark', 'Pikó Márk', 'DAMIT Informatika Kft.', 'mark.piko@raspartner.hu'),
(602, 'horvath.antal', 'Horváth Antal', NULL, 'antal.horvath@raspartner.hu'),
(603, 'bence.flaskar', 'Flaskár Bence', 'Profession.hu Kft.', 'bence.flaskar@profession.hu'),
(604, 'kuszal.ambrus', 'Kuszál Ambrus', 'DAMIT Informatika Kft.', 'ambrus.domonkos@raspartner.hu'),
(605, 'katinka.jeszenszki', 'Jeszenszki Katinka', 'Profession.hu Kft.', 'katinka.jeszenszki@profession.hu'),
(606, 'vagi.tamas', 'Vági Tamás', 'RAS Magyarország Kft.', 'tamas.vagi@ringieraxelspringer.hu'),
(607, 'gombos.attila', 'Gombos Attila', 'RAS Magyarország Kft.', 'attila.gombos@ringieraxelspringer.hu'),
(608, 'didics.gloria', 'Didics Glória', 'RAS Magyarország Kft.', 'gloria.didics@ringieraxelspringer.hu'),
(609, 'reka.ecsedi-barabas', 'Barabás Réka', 'Profession.hu Kft.', 'reka.barabas@profession.hu'),
(610, 'gabor.budai', 'Budai Gábor', 'Profession.hu Kft.', 'gabor.budai@profession.hu'),
(611, 'balazs.krizsan', 'Krizsán Balázs', 'Profession.hu Kft.', 'balazs.krizsan@profession.hu'),
(612, 'Porkolab.Zsofi', 'Porkoláb Zsófi', 'Blikk Kft.', 'zsofia.porkolab@blikk.hu'),
(613, 'kristof.dobokay', 'Dobokay Kristóf', 'Profession.hu Kft.', 'kristof.dobokay@profession.hu'),
(614, 'szandra.sari', 'Sári Petra Szandra', 'Profession.hu Kft.', 'szandra.sari@profession.hu'),
(615, 'Szarvas.Melinda', 'Szarvas Melinda', 'RAS Magyarország Kft.', 'melinda.szarvas@ringieraxelspringer.hu'),
(616, 'k.dobokay', 'Dobokay Kristóf - privát', 'Profession.hu Kft.', 'k.dobokay@profession.hu'),
(617, 'milan.matis', 'Mátis Milán', 'Profession.hu Kft.', 'milan.matis@profession.hu'),
(618, 'varnai.eniko', 'Várnai Enikő', 'RAS Magyarország Kft.', 'eniko.varnai@ringieraxelspringer.hu'),
(619, 'rita.sanda', 'Sanda Rita', 'Profession.hu Kft.', 'rita.sanda@profession.hu'),
(620, 'barczag.andrea', 'Barczag Andrea', 'HarperCollins Magyarország Kft.', 'andrea.barczag@ringieraxelspringer.hu'),
(621, 'soponyai.viktor', 'Soponyai Viktor', 'RAS Magyarország Kft.', 'viktor.soponyai@raspartner.hu'),
(622, 'horvath.borbala', 'Horváth Borbála', 'RAS Magyarország Kft.', 'borbala.horvath@ringieraxelspringer.hu'),
(623, 'Regenyi.Marta', 'Regényi Márta', 'RAS Magyarország Kft.', 'marta.regenyi@raspartner.hu'),
(624, 'vegh.veronika', 'Végh Veronika', 'RAS Magyarország kft.', 'veronika.vegh@ringieraxelspringer.hu'),
(625, 'batha.peter', 'Batha Péter', 'RAS Magyarország Kft.', 'peter.batha@ringieraxelspringer.hu'),
(626, 'varga.gabor', 'Varga Gábor', 'RAS Magyarország Kft.', 'gabor.varga@ringieraxelspringer.hu'),
(627, 'gal.peter', 'Gál Péter Márk', 'RAS Magyarország Kft.', 'peter.gal@ringieraxelspringer.hu'),
(628, 'hirdetesteszt3.probo', 'hirdetesteszt3.probos', NULL, 'hirdetesteszt3@profession.hu'),
(629, 'dorina.heszler', 'Heszler Dorina', 'Profession.hu Kft.', 'dorina.heszler@profession.hu'),
(630, 'edit.rumy', 'Rumy Edit', 'Profession.hu Kft.', 'edit.rumy@profession.hu'),
(631, 'crm.pm', 'crm pm', NULL, 'crm.pm@profession.hu'),
(632, 'marietta.kleri', 'Kléri Marietta', 'Profession.hu Kft.', 'marietta.kleri@profession.hu'),
(633, 'brigitta.lancos', 'Láncos Brigitta', 'Profession.hu Kft.', 'brigitta.lancos@profession.hu'),
(634, 'baranyecz.janos', 'Baranyecz János', 'RAS Magyarország Kft.', 'janos.baranyecz@ringieraxelspringer.hu'),
(635, 'benedek.toth', 'Tóth Benedek', 'Profession.hu Kft.', 'benedek.toth@profession.hu'),
(636, 'adam.fulop', 'Fülöp Ádám', 'Profession.hu Kft.', 'adam.fulop@profession.hu'),
(637, 'LQ', 'LQ@profession.hu', NULL, 'LQ@profession.hu'),
(638, 'lilla.lazar', 'Lázár Lilla', 'Profession.hu Kft.', 'lilla.lazar@profession.hu'),
(639, 'csaba.lukacs', 'Lukács Csaba', 'Profession.hu Kft.', 'csaba.lukacs@profession.hu'),
(640, 'borso.robert', 'Borsó Róbert', 'DAMIT Informatika Kft.', 'robert.borso@raspartner.hu'),
(641, 'profession.gdpr', 'Profession GDPR', NULL, 'gdpr@profession.hu'),
(642, 'molnar.szabolcs', 'Molnár Szabolcs', 'Blikk Kft.', 'szabolcs.molnar@blikk.hu'),
(643, 'csaba.jaszapathy', 'Jászapáthy Csaba', 'Profession.hu Kft.', 'csaba.jaszapathy@profession.hu'),
(644, 'joo.laszlo', 'Joó László', 'RAS Magyarország Kft.', 'laszlo.joo@ringieraxelspringer.hu'),
(645, 'xml', 'Profession.hu XML Support Team', NULL, 'xml@profession.hu'),
(646, 'varga.imre', 'Varga Imre', 'Blikk Kft.', 'imre.varga@blikk.hu'),
(647, 'nagy.andrea', 'Nagy Andrea', 'RAS Magyarország Kft.', 'andrea.nagy@ringieraxelspringer.hu'),
(648, 'roland.eikel', 'Eikel Roland', 'Profession.hu Kft.', 'roland.eikel@profession.hu'),
(649, 'kata.nagy', 'Nagy Kata', 'Profession.hu Kft.', 'kata.nagy@profession.hu'),
(650, 'orsolya.balla', 'Balla Orsolya', 'Profession.hu Kft.', 'orsolya.balla@profession.hu'),
(651, 'robert.kadelka', 'Kadelka Róbert', NULL, 'robert.kadelka@profession.hu'),
(652, 'daniel.toth', 'Tóth Dániel', NULL, 'daniel.toth@profession.hu'),
(653, 'balazs.spanyik', 'Spányik Balázs', 'Profession.hu Kft.', 'balazs.spanyik@profession.hu'),
(654, 'tamas.szilardi', 'Szilárdi Tamás', 'Profession.hu Kft.', 'tamas.szilardi@profession.hu'),
(655, 'vera.balo', 'Baló Vera', 'Profession.hu Kft.', 'vera.balo@profession.hu'),
(656, 'profession_szallito', 'Profession Szállítói Számlakezelés', NULL, 'szallito@profession.hu'),
(657, 'tamara.arva', 'Árva Tamara', 'Profession.hu Kft.', 'tamara.arva@profession.hu'),
(658, 'profession.jelentkez', 'jelentkezes@profession.hu', NULL, 'jelentkezes@profession.hu'),
(659, 'Journal180427', 'Journal180427', NULL, 'Journal180427@as.local'),
(660, 'zsoltf', 'Fodor Zsolt – Munkahelyek.hu', NULL, 'zsoltf@profession.hu'),
(661, 'dora.benczik', 'Benczik Dóra Zsuzsanna', 'Profession.hu Kft.', 'dora.benczik@profession.hu'),
(662, 'tanacsado', 'Tanácsadó Profession', 'Profession.hu Kft.', 'tanacsado@profession.hu'),
(663, 'gabriella.bacsi', 'Bácsi Gabriella', 'Profession.hu Kft.', 'gabriella.bacsi@profession.hu'),
(664, 'karrier.karrier', 'karrier@profession.hu', 'Profession.hu Kft.', 'karrier@profession.hu'),
(665, 'andrea2.nagy', 'Nagy Andrea2', 'RAS Magyarország Kft.', 'andrea.bnagy@ringieraxelspringer.hu'),
(666, 'zsofia.bitai', 'Bitai Zsófia', 'Profession.hu Kft.', 'zsofia.bitai@profession.hu'),
(667, 'prof.adatvedelem', 'Adatvédelem Profession', 'Profession.hu Kft.', 'adatvedelem@profession.hu'),
(668, 'zsofia.tanarki', 'Tanárki Zsófia', 'Profession.hu Kft.', 'zsofia.tanarki@profession.hu'),
(669, 'vivien.fejes', 'Fejes Vivien', 'Profession.hu Kft.', 'vivien.fejes@profession.hu'),
(670, 'prof.jog', 'Lilla Cs. Tóth', 'Profession.hu Kft.', 'jog@profession.hu'),
(671, 'richard.czinege', 'Czinege Richárd', 'Profession.hu Kft.', 'richard.czinege@profession.hu'),
(672, 'krisztina.kada', 'Kada Krisztina', 'Profession.hu Kft.', 'krisztina.kada@profession.hu'),
(673, 'hajnalka.holovitz', 'Holovitz Hajnalka', 'Profession.hu Kft.', 'hajnalka.holovitz@profession.hu'),
(674, 'h.holovitz', 'Holovitz Hajnalka privát', NULL, 'h.holovitz@profession.hu'),
(675, 'laszlo.lipcsei', 'Lipcsei László Péter', 'Profession.hu Kft.', 'laszlo.lipcsei@profession.hu'),
(676, 'ivor.szaniszlo', 'Ivor Szaniszló', 'RAS Magyarország Kft.', 'szaniszlo.ivor@ringieraxelspringer.hu'),
(677, 'eva.jofoldiszabo', 'Jóföldi-Szabó Éva', 'Profession.hu Kft.', 'eva.jofoldiszabo@profession.hu'),
(678, 'deli.daniel', 'Deli Dániel', NULL, 'daniel.deli@ringieraxelspringer.hu'),
(679, 'zsolt.nagymengyi', 'Nagy-Mengyi Zsolt', 'Profession.hu Kft.', 'zsolt.nagymengyi@profession.hu'),
(680, 'reka.dobronte', 'Döbrönte Réka', 'Profession.hu Kft.', 'reka.dobronte@profession.hu'),
(681, 'tamas.gabor', 'Gábor Tamás', NULL, 'gabor.tamas@profession.hu'),
(682, 'gergely.dankhazi', 'Dankházi Gergely', NULL, 'gergely.dankhazi@profession.hu'),
(683, 'tamas.babos', 'Babos Tamás', 'Profession.hu Kft.', 'tamas.babos@profession.hu'),
(684, 'Lasanyi.Csaba', 'Lasányi Csaba', 'Blikk Kft.', 'csaba.lasanyi@blikk.hu'),
(685, 'szeiler.kira', 'Szeiler Kíra', 'RAS Magyarország Kft.', 'kira.szeiler@ringieraxelspringer.hu'),
(686, 'dietrich.attila', 'Dietrich Attila', 'RAS Magyarország Kft.', 'attila.dietrich@ringieraxelspringer.hu'),
(687, 'huzsvar.edit', 'Huzsvár Edit', 'RAS Magyarország Kft.', 'edit.huzsvar@ringieraxelspringer.hu'),
(688, 'balla.gabor', 'Balla Gábor', 'RAS Magyarország Kft.', 'gabor.balla@ras-oander.com'),
(689, 'akos.gebri', 'Gebri Ákos', 'Profession.hu Kft.', 'akos.gebri@profession.hu'),
(690, 'szabo.anna', 'Szabó Anna', 'RAS Magyarország Kft.', 'anna.szabo@ringieraxelspringer.hu'),
(691, 'akos.sarenczky', 'Ákos Sarenczky', 'Profession.hu Kft.', 'akos.sarenczky@profession.hu'),
(692, 'noreply.probos', 'Probos Noreply', 'Profession.hu Kft.', 'noreply.probos@profession.hu'),
(693, 'zsolt.polacsek', 'Polacsek Zsolt', 'Profession.hu Kft.', 'zsolt.polacsek@profession.hu'),
(694, 'balazs.kristok', 'Kristók Balázs', 'Profession.hu Kft.', 'balazs.kristok@profession.hu'),
(695, 'kralik.dora', 'Králik Dóra', 'RAS Magyarország kft.', 'dora.kralik@ringieraxelspringer.hu'),
(696, 'ober.gergely', 'dr. Ober Gergely', 'RAS Magyarország Kft.', 'gergely.ober@ringieraxelspringer.hu'),
(697, 'laszlo.peto', 'Pető László', 'Profession.hu Kft.', 'laszlo.peto@profession.hu'),
(698, 'greta.baranyai', 'Baranyai Gréta', 'Profession.hu Kft.', 'greta.baranyai@profession.hu'),
(699, 'rendezveny', 'Profession Rendezvény', 'Profession.hu Kft.', 'rendezveny@profession.hu'),
(700, 'toth-antal.rebeka', 'Tóth-Antal Rebeka', 'RAS Magyarország Kft.', 'rebeka.toth-antal@ringieraxelspringer.hu'),
(701, 'account5', 'profession account5', 'Profession.hu Kft.', 'account5@profession.hu'),
(702, 'zsolt.barta', 'Barta Zsolt', 'Profession.hu Kft.', 'zsolt.barta@profession.hu'),
(703, 'tamas.dohany', 'Dohány Tamás', 'Profession.hu Kft.', 'tamas.dohany@profession.hu'),
(704, 'bettina.bence', 'Bence Bettina', 'Profession.hu Kft.', 'bettina.bence@profession.hu'),
(705, 'jacint.magyar', 'Magyar Jácint', 'Profession.hu Kft.', 'jacint.magyar@profession.hu'),
(706, 'fejes.ivett', 'Fejes Ivett', 'HarperCollins Magyarország Kft.', 'ivett.fejes@harpercollins.hu'),
(707, 'alexandra.havas', 'Havas Alexandra', 'Profession.hu Kft.', 'alexandra.havas@profession.hu'),
(708, 'profession.account3', 'profession account3', 'Profession.hu Kft.', 'account3@profession.hu'),
(709, 'evelin.nagy', 'Nagy Evelin', 'Profession.hu Kft.', 'evelin.nagy@profession.hu'),
(710, 'balint.vigh', 'Vigh Bálint', 'Profession.hu Kft.', 'balint.vigh@profession.hu'),
(711, 'e.nagy', 'Nagy Evelin Privát', 'Profession.hu Kft.', 'e.nagy@profession.hu'),
(712, 'scantomail', 'ScanToMail Test', NULL, 'diana.dittrich@raspartner.hu'),
(713, 'barna.bodo', 'Bodó Barna', 'Profession.hu Kft.', 'barna.bodo@profession.hu'),
(714, 'kristof.torma', 'Torma Kristóf', 'Profession.hu Kft.', 'kristof.torma@profession.hu'),
(715, 'alexander.csontos', 'Csontos Alexander', 'Profession.hu Kft.', 'alexander.csontos@profession.hu'),
(716, 'szanto.tamas', 'Szántó Tamás', 'RAS Magyarország Kft.', 'tamas.szanto@raspartner.hu'),
(717, 'laszlo.vukovich', 'Vukovich László', 'Profession.hu Kft.', 'laszlo.vukovich@profession.hu'),
(718, 'levai.zsuzsanna', 'Lévai Zsuzsanna', 'RAS Magyarország Kft.', 'zsuzsanna.levai@ringieraxelspringer.hu'),
(719, 'csintalan.eszter', 'Csintalan Eszter', 'RAS Magyarország Kft.', 'eszter.csintalan@ringieraxelspringer.hu'),
(720, 'bazso.david', 'Bazsó Dávid', 'Blikk Kft.', 'david.bazso@blikk.hu'),
(721, 'bence.molnar', 'Molnár Bence', 'Profession.hu Kft.', 'bence.molnar@profession.hu'),
(722, 'attila.potocki', 'Potocki Attila', NULL, 'attila.potocki@as.local'),
(723, 'zsolt.borbely', 'Borbély Zsolt', 'Profession.hu Kft.', 'zsolt.borbely@profession.hu'),
(724, 'david.chyba', 'Chyba Dávid', 'Profession.hu Kft.', 'david.chyba@profession.hu'),
(725, 'robert.lang', 'Láng Róbert', 'Profession.hu Kft.', 'robert.lang@profession.hu'),
(726, 'gyula.garaci', 'Garaci Gyula', 'Profession.hu Kft.', 'gyula.garaci@profession.hu'),
(727, 'd.chyba', 'Chyba Dávid Privát', 'Profession.hu Kft.', 'd.chyba@profession.hu'),
(728, 'kun.mate', 'Kun Máté', 'RAS Magyarország Kft.', 'mate.kun@ringieraxelspringer.hu'),
(729, 'lukacs.angelika', 'Lukács Angelika', 'RAS Magyarország Kft.', 'angelika.lukacs@ringieraxelspringer.hu'),
(730, 'blikkgyakornok6', 'Blikk Gyakornok6', 'Blikk Kft.', 'blikkgyakornok6@blikkpartner.hu'),
(731, NULL, NULL, NULL, NULL),
(732, NULL, NULL, NULL, NULL),
(733, NULL, NULL, NULL, NULL),
(734, NULL, NULL, NULL, NULL),
(735, NULL, NULL, NULL, NULL),
(736, NULL, NULL, NULL, NULL),
(737, NULL, NULL, NULL, NULL),
(738, NULL, NULL, NULL, NULL),
(739, NULL, NULL, NULL, NULL),
(740, NULL, NULL, NULL, NULL),
(741, NULL, NULL, NULL, NULL),
(742, NULL, NULL, NULL, NULL),
(743, NULL, NULL, NULL, NULL),
(744, NULL, NULL, NULL, NULL),
(745, NULL, NULL, NULL, NULL),
(746, NULL, NULL, NULL, NULL),
(747, NULL, NULL, NULL, NULL),
(748, NULL, NULL, NULL, NULL),
(749, NULL, NULL, NULL, NULL),
(750, NULL, NULL, NULL, NULL),
(751, NULL, NULL, NULL, NULL),
(752, NULL, NULL, NULL, NULL),
(753, NULL, NULL, NULL, NULL),
(754, NULL, NULL, NULL, NULL),
(755, NULL, NULL, NULL, NULL),
(756, NULL, NULL, NULL, NULL),
(757, NULL, NULL, NULL, NULL),
(758, NULL, NULL, NULL, NULL),
(759, NULL, NULL, NULL, NULL),
(760, NULL, NULL, NULL, NULL),
(761, NULL, NULL, NULL, NULL),
(762, NULL, NULL, NULL, NULL),
(763, NULL, NULL, NULL, NULL),
(764, NULL, NULL, NULL, NULL),
(765, NULL, NULL, NULL, NULL),
(766, NULL, NULL, NULL, NULL),
(767, NULL, NULL, NULL, NULL),
(768, NULL, NULL, NULL, NULL),
(769, NULL, NULL, NULL, NULL),
(770, NULL, NULL, NULL, NULL),
(771, NULL, NULL, NULL, NULL),
(772, NULL, NULL, NULL, NULL),
(773, NULL, NULL, NULL, NULL),
(774, NULL, NULL, NULL, NULL),
(775, NULL, NULL, NULL, NULL),
(776, NULL, NULL, NULL, NULL),
(777, NULL, NULL, NULL, NULL),
(778, NULL, NULL, NULL, NULL),
(779, NULL, NULL, NULL, NULL),
(780, NULL, NULL, NULL, NULL),
(781, NULL, NULL, NULL, NULL),
(782, NULL, NULL, NULL, NULL),
(783, NULL, NULL, NULL, NULL),
(784, NULL, NULL, NULL, NULL),
(785, NULL, NULL, NULL, NULL),
(786, NULL, NULL, NULL, NULL),
(787, NULL, NULL, NULL, NULL),
(788, NULL, NULL, NULL, NULL),
(789, NULL, NULL, NULL, NULL),
(790, NULL, NULL, NULL, NULL),
(791, NULL, NULL, NULL, NULL),
(792, NULL, NULL, NULL, NULL),
(793, NULL, NULL, NULL, NULL),
(794, NULL, NULL, NULL, NULL),
(795, NULL, NULL, NULL, NULL);

ALTER TABLE `voters`
  ADD PRIMARY KEY (`id`);

ALTER TABLE `voters`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;COMMIT;